# Regression Predict Student Solution

© Explore Data Science Academy

---
### Honour Code

I {**YOUR NAME, YOUR SURNAME**}, confirm - by submitting this document - that the solutions in this notebook are a result of my own work and that I abide by the [EDSA honour code](https://drive.google.com/file/d/1QDCjGZJ8-FmJE3bZdIQNwnJyQKPhHZBn/view?usp=sharing).

Non-compliance with the honour code constitutes a material breach of contract.

### Predict Overview: Spain Electricity Shortfall Challenge

The government of Spain is considering an expansion of it's renewable energy resource infrastructure investments. As such, they require information on the trends and patterns of the countries renewable sources and fossil fuel energy generation. Your company has been awarded the contract to:

- 1. analyse the supplied data;
- 2. identify potential errors in the data and clean the existing data set;
- 3. determine if additional features can be added to enrich the data set;
- 4. build a model that is capable of forecasting the three hourly demand shortfalls;
- 5. evaluate the accuracy of the best machine learning model;
- 6. determine what features were most important in the model’s prediction decision, and
- 7. explain the inner working of the model to a non-technical audience.

Formally the problem statement was given to you, the senior data scientist, by your manager via email reads as follow:

> In this project you are tasked to model the shortfall between the energy generated by means of fossil fuels and various renewable sources - for the country of Spain. The daily shortfall, which will be referred to as the target variable, will be modelled as a function of various city-specific weather features such as `pressure`, `wind speed`, `humidity`, etc. As with all data science projects, the provided features are rarely adequate predictors of the target variable. As such, you are required to perform feature engineering to ensure that you will be able to accurately model Spain's three hourly shortfalls.
 
On top of this, she has provided you with a starter notebook containing vague explanations of what the main outcomes are.

<a id="cont"></a>

## Table of Contents

<a href=#one>1. Importing Packages</a>

<a href=#two>2. Loading Data</a>

<a href=#three>3. Exploratory Data Analysis (EDA)</a>

<a href=#four>4. Data Engineering</a>

<a href=#five>5. Modeling</a>

<a href=#six>6. Model Performance</a>

<a href=#seven>7. Model Explanations</a>

 <a id="one"></a>
## 1. Importing Packages
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Importing Packages ⚡ |
| :--------------------------- |
| In this section you are required to import, and briefly discuss, the libraries that will be used throughout your analysis and modelling. |

---

In [398]:
# Libraries for data loading, data manipulation and data visulisation
import numpy as np
import pandas as pd

# Libraries for data preparation and model building
import seaborn as sns
sns.set_style('darkgrid')
import matplotlib.pyplot as plt
%matplotlib
# Setting global constants to ensure notebook results are reproducible
PARAMETER_CONSTANT =pd
pd.set_option('max_columns', None)
pd.set_option('max_rows', 90)

Using matplotlib backend: Qt5Agg

<a id="two"></a>
## 2. Loading the Data
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Loading the data ⚡ |
| :--------------------------- |
| In this section you are required to load the data from the `df_train` file into a DataFrame. |

---

In [399]:
train0=pd.read_csv('df_train.csv')
test0=pd.read_csv('df_test.csv')

<a id="three"></a>
## 3. Exploratory Data Analysis (EDA)
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Exploratory data analysis ⚡ |
| :--------------------------- |
| In this section, you are required to perform an in-depth analysis of all the variables in the DataFrame. |

---

In [400]:
train0.head()

,Unnamed: 0,time,Madrid_wind_speed,Valencia_wind_deg,Bilbao_rain_1h,Valencia_wind_speed,Seville_humidity,Madrid_humidity,Bilbao_clouds_all,Bilbao_wind_speed,Seville_clouds_all,Bilbao_wind_deg,Barcelona_wind_speed,Barcelona_wind_deg,Madrid_clouds_all,Seville_wind_speed,Barcelona_rain_1h,Seville_pressure,Seville_rain_1h,Bilbao_snow_3h,Barcelona_pressure,Seville_rain_3h,Madrid_rain_1h,Barcelona_rain_3h,Valencia_snow_3h,Madrid_weather_id,Barcelona_weather_id,Bilbao_pressure,Seville_weather_id,Valencia_pressure,Seville_temp_max,Madrid_pressure,Valencia_temp_max,Valencia_temp,Bilbao_weather_id,Seville_temp,Valencia_humidity,Valencia_temp_min,Barcelona_temp_max,Madrid_temp_max,Barcelona_temp,Bilbao_temp_min,Bilbao_temp,Barcelona_temp_min,Bilbao_temp_max,Seville_temp_min,Madrid_temp,Madrid_temp_min,load_shortfall_3h
0,0,2015-01-01 03:00:00,0.666667,level_5,0.0,0.666667,74.333333,64.000000,0.0,1.000000,0.0,223.333333,6.333333,42.666667,0.0,3.333333,0.0,sp25,0.0,0.0,1036.333333,0.0,0.0,0.0,0.0,800.0,800.0,1035.000000,800.0,1002.666667,274.254667,971.333333,269.888000,269.888000,800.0,274.254667,75.666667,269.888000,281.013000,265.938000,281.013000,269.338615,269.338615,281.013000,269.338615,274.254667,265.938000,265.938000,6715.666667
1,1,2015-01-01 06:00:00,0.333333,level_10,0.0,1.666667,78.333333,64.666667,0.0,1.000000,0.0,221.000000,4.000000,139.000000,0.0,3.333333,0.0,sp25,0.0,0.0,1037.333333,0.0,0.0,0.0,0.0,800.0,800.0,1035.666667,800.0,1004.333333,274.945000,972.666667,271.728333,271.728333,800.0,274.945000,71.000000,271.728333,280.561667,266.386667,280.561667,270.376000,270.376000,280.561667,270.376000,274.945000,266.386667,266.386667,4171.666667
2,2,2015-01-01 09:00:00,1.000000,level_9,0.0,1.000000,71.333333,64.333333,0.0,1.000000,0.0,214.333333,2.000000,326.000000,0.0,2.666667,0.0,sp25,0.0,0.0,1038.000000,0.0,0.0,0.0,0.0,800.0,800.0,1036.000000,800.0,1005.333333,278.792000,974.000000,278.008667,278.008667,800.0,278.792000,65.666667,278.008667,281.583667,272.708667,281.583667,275.027229,275.027229,281.583667,275.027229,278.792000,272.708667,272.708667,4274.666667
3,3,2015-01-01 12:00:00,1.000000,level_8,0.0,1.000000,65.333333,56.333333,0.0,1.000000,0.0,199.666667,2.333333,273.000000,0.0,4.000000,0.0,sp25,0.0,0.0,1037.000000,0.0,0.0,0.0,0.0,800.0,800.0,1036.000000,800.0,1009.000000,285.394000,994.666667,284.899552,284.899552,800.0,285.394000,54.000000,284.899552,283.434104,281.895219,283.434104,281.135063,281.135063,283.434104,281.135063,285.394000,281.895219,281.895219,5075.666667
4,4,2015-01-01 15:00:00,1.000000,level_7,0.0,1.000000,59.000000,57.000000,2.0,0.333333,0.0,185.000000,4.333333,260.000000,0.0,3.000000,0.0,sp25,0.0,0.0,1035.000000,0.0,0.0,0.0,0.0,800.0,800.0,1035.333333,800.0,NaN,285.513719,1035.333333,283.015115,283.015115,800.0,285.513719,58.333333,283.015115,284.213167,280.678437,284.213167,282.252063,282.252063,284.213167,282.252063,285.513719,280.678437,280.678437,6620.666667

In [401]:
test0.head()

,Unnamed: 0,time,Madrid_wind_speed,Valencia_wind_deg,Bilbao_rain_1h,Valencia_wind_speed,Seville_humidity,Madrid_humidity,Bilbao_clouds_all,Bilbao_wind_speed,Seville_clouds_all,Bilbao_wind_deg,Barcelona_wind_speed,Barcelona_wind_deg,Madrid_clouds_all,Seville_wind_speed,Barcelona_rain_1h,Seville_pressure,Seville_rain_1h,Bilbao_snow_3h,Barcelona_pressure,Seville_rain_3h,Madrid_rain_1h,Barcelona_rain_3h,Valencia_snow_3h,Madrid_weather_id,Barcelona_weather_id,Bilbao_pressure,Seville_weather_id,Valencia_pressure,Seville_temp_max,Madrid_pressure,Valencia_temp_max,Valencia_temp,Bilbao_weather_id,Seville_temp,Valencia_humidity,Valencia_temp_min,Barcelona_temp_max,Madrid_temp_max,Barcelona_temp,Bilbao_temp_min,Bilbao_temp,Barcelona_temp_min,Bilbao_temp_max,Seville_temp_min,Madrid_temp,Madrid_temp_min
0,8763,2018-01-01 00:00:00,5.000000,level_8,0.0,5.000000,87.000000,71.333333,20.000000,3.000000,0.000000,193.333333,4.000000,176.666667,0.0,1.000000,0.0,sp25,0.0,0,1017.333333,0.0,0.0,0.0,0,800.0,800.000000,1025.666667,800.000000,NaN,284.483333,1030.000000,287.483333,287.483333,801.000000,283.673333,46.333333,287.483333,287.816667,280.816667,287.356667,276.150000,280.380000,286.816667,285.150000,283.150000,279.866667,279.150000
1,8764,2018-01-01 03:00:00,4.666667,level_8,0.0,5.333333,89.000000,78.000000,0.000000,3.666667,0.000000,143.333333,4.666667,266.666667,0.0,0.666667,0.0,sp25,0.0,0,1020.333333,0.0,0.0,0.0,0,800.0,800.333333,1026.666667,800.000000,NaN,282.483333,1030.333333,284.150000,284.150000,721.000000,281.673333,53.666667,284.150000,284.816667,280.483333,284.190000,277.816667,281.010000,283.483333,284.150000,281.150000,279.193333,278.150000
2,8765,2018-01-01 06:00:00,2.333333,level_7,0.0,5.000000,89.000000,89.666667,0.000000,2.333333,6.666667,130.000000,4.000000,263.333333,0.0,0.666667,0.0,sp25,0.0,0,1023.000000,0.0,0.0,0.0,0,800.0,800.000000,1025.333333,800.333333,NaN,280.816667,1030.666667,282.816667,282.816667,800.000000,280.613333,42.000000,282.816667,284.483333,276.483333,283.150000,276.816667,279.196667,281.816667,282.150000,280.483333,276.340000,276.150000
3,8766,2018-01-01 09:00:00,2.666667,level_7,0.0,5.333333,93.333333,82.666667,26.666667,5.666667,6.666667,196.666667,2.333333,86.666667,0.0,1.333333,0.0,sp25,0.0,0,1025.666667,0.0,0.0,0.0,0,800.0,800.000000,1025.000000,800.333333,NaN,281.150000,1032.333333,283.483333,283.483333,801.333333,279.936667,45.000000,283.483333,284.150000,277.150000,283.190000,279.150000,281.740000,282.150000,284.483333,279.150000,275.953333,274.483333
4,8767,2018-01-01 12:00:00,4.000000,level_7,0.0,8.666667,65.333333,64.000000,26.666667,10.666667,0.000000,233.333333,4.666667,283.333333,0.0,1.000000,0.0,sp25,0.0,0,1026.000000,0.0,0.0,0.0,0,800.0,800.333333,1022.333333,800.000000,NaN,287.150000,1032.333333,287.150000,287.150000,801.333333,285.570000,41.000000,287.150000,287.483333,281.150000,286.816667,281.816667,284.116667,286.150000,286.816667,284.483333,280.686667,280.150000

In [402]:
# evaluate correlation
train0.describe()

,Unnamed: 0,Madrid_wind_speed,Bilbao_rain_1h,Valencia_wind_speed,Seville_humidity,Madrid_humidity,Bilbao_clouds_all,Bilbao_wind_speed,Seville_clouds_all,Bilbao_wind_deg,Barcelona_wind_speed,Barcelona_wind_deg,Madrid_clouds_all,Seville_wind_speed,Barcelona_rain_1h,Seville_rain_1h,Bilbao_snow_3h,Barcelona_pressure,Seville_rain_3h,Madrid_rain_1h,Barcelona_rain_3h,Valencia_snow_3h,Madrid_weather_id,Barcelona_weather_id,Bilbao_pressure,Seville_weather_id,Valencia_pressure,Seville_temp_max,Madrid_pressure,Valencia_temp_max,Valencia_temp,Bilbao_weather_id,Seville_temp,Valencia_humidity,Valencia_temp_min,Barcelona_temp_max,Madrid_temp_max,Barcelona_temp,Bilbao_temp_min,Bilbao_temp,Barcelona_temp_min,Bilbao_temp_max,Seville_temp_min,Madrid_temp,Madrid_temp_min,load_shortfall_3h
count,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8.763000e+03,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,6695.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000,8763.000000
mean,4381.000000,2.425729,0.135753,2.586272,62.658793,57.414717,43.469132,1.850356,13.714748,158.957511,2.870497,190.544848,19.473392,2.425045,0.128906,0.039439,0.031912,1.377965e+03,0.000243,0.037818,0.000439,0.000205,773.527594,765.979687,1017.739549,774.658818,1012.051407,297.479527,1010.316920,291.337233,290.592152,724.722362,293.978903,65.247727,289.867648,291.157644,289.540309,289.855459,285.017973,286.422929,288.447422,287.966027,291.633356,288.419439,287.202203,10673.857612
std,2529.804538,1.850371,0.374901,2.411190,22.621226,24.335396,32.551044,1.695888,24.272482,102.056299,1.792197,89.077337,28.053660,1.672895,0.634730,0.175857,0.557264,1.407314e+04,0.003660,0.152639,0.003994,0.011866,77.313315,88.142235,10.046124,71.940009,9.506214,8.875812,22.198555,7.565692,7.162274,115.846537,7.920986,19.262322,6.907402,7.273538,9.752047,6.528111,6.705672,6.818682,6.102593,7.105590,8.178220,9.346796,9.206237,5218.046404
min,0.000000,0.000000,0.000000,0.000000,8.333333,6.333333,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.706667e+02,0.000000,0.000000,0.000000,0.000000,211.000000,200.666667,971.333333,200.000000,972.666667,272.063000,927.666667,269.888000,269.888000,207.333333,272.063000,10.333333,269.888000,272.150000,264.983333,270.816667,264.483333,267.483333,269.483333,269.063000,270.150000,264.983333,264.983333,-6618.000000
25%,2190.500000,1.000000,0.000000,1.000000,44.333333,36.333333,10.000000,0.666667,0.000000,73.333333,1.666667,118.166667,0.000000,1.000000,0.000000,0.000000,0.000000,1.014000e+03,0.000000,0.000000,0.000000,0.000000,800.000000,800.000000,1013.000000,800.000000,1010.333333,291.312750,1012.333333,285.550167,285.150000,700.333333,288.282917,51.333333,284.783333,285.483333,282.150000,284.973443,280.085167,281.374167,284.150000,282.836776,285.816667,281.404281,280.299167,7390.333333
50%,4381.000000,2.000000,0.000000,1.666667,65.666667,58.000000,45.000000,1.000000,0.000000,147.000000,2.666667,200.000000,0.000000,2.000000,0.000000,0.000000,0.000000,1.018000e+03,0.000000,0.000000,0.000000,0.000000,800.000000,800.333333,1019.000000,800.000000,1015.000000,297.101667,1017.333333,291.037000,290.176667,800.000000,293.323333,67.000000,289.550000,290.150000,288.116177,289.416667,284.816667,286.158333,288.150000,287.630000,290.816667,287.053333,286.083333,11114.666667
75%,6571.500000,3.333333,0.100000,3.666667,82.000000,78.666667,75.000000,2.666667,20.000000,234.000000,4.000000,260.000000,33.333333,3.333333,0.000000,0.000000,0.000000,1.022000e+03,0.000000,0.000000,0.000000,0.000000,800.666667,801.000000,1024.000000,800.000000,1018.000000,304.150000,1022.000000,297.248333,296.056667,801.666667,299.620333,81.333333,294.820000,296.855000,296.816667,294.909000,289.816667,291.034167,292.966667,292.483333,297.150000,295.154667,293.884500,14498.166667
max,8762.000000,13.000000,3.000000,52.000000,100.000000,100.000000,100.000000,12.666667,97.333333,359.333333,12.666667,360.000000,100.000000,11.666667,12.000000,3.000000,21.300000,1.001411e+06,0.093333,3.000000,0.093000,0.791667,804.000000,804.000000,1042.000000,804.000000,1021.666667,320.483333,1038.000000,314.263333,310.426667,804.000000,314.976667,100.000000,310.272000,314.076667,314.483333,307.316667,309.816667,310.710000,304.816667,317.966667,314.816667,313.133333,310.383333,31904.000000

In [403]:
train0.corr()

,Unnamed: 0,Madrid_wind_speed,Bilbao_rain_1h,Valencia_wind_speed,Seville_humidity,Madrid_humidity,Bilbao_clouds_all,Bilbao_wind_speed,Seville_clouds_all,Bilbao_wind_deg,Barcelona_wind_speed,Barcelona_wind_deg,Madrid_clouds_all,Seville_wind_speed,Barcelona_rain_1h,Seville_rain_1h,Bilbao_snow_3h,Barcelona_pressure,Seville_rain_3h,Madrid_rain_1h,Barcelona_rain_3h,Valencia_snow_3h,Madrid_weather_id,Barcelona_weather_id,Bilbao_pressure,Seville_weather_id,Valencia_pressure,Seville_temp_max,Madrid_pressure,Valencia_temp_max,Valencia_temp,Bilbao_weather_id,Seville_temp,Valencia_humidity,Valencia_temp_min,Barcelona_temp_max,Madrid_temp_max,Barcelona_temp,Bilbao_temp_min,Bilbao_temp,Barcelona_temp_min,Bilbao_temp_max,Seville_temp_min,Madrid_temp,Madrid_temp_min,load_shortfall_3h
Unnamed: 0,1.000000,-0.109288,-0.249633,-0.090161,-0.079025,-0.103359,-0.068123,0.049197,-0.140583,-0.155738,-0.218781,-0.140449,-0.116928,-0.093926,-0.075692,-0.075340,-0.092377,-0.040157,-0.082525,-0.068980,-0.104326,-0.028130,0.047202,0.034761,-0.022475,0.072472,0.267772,0.039424,0.385578,0.087002,0.135294,0.192485,0.042897,0.023917,0.185468,0.047417,0.093378,0.068078,0.028698,0.081799,0.103436,0.146216,0.037487,0.088439,0.085197,0.192612
Madrid_wind_speed,-0.109288,1.000000,0.259719,0.513092,-0.117892,-0.137092,0.244001,0.377854,0.191251,0.270950,0.294640,-0.095380,0.230126,0.434104,0.062758,0.108413,0.071183,0.011134,0.004795,0.150446,-0.014644,0.021660,-0.169358,-0.099582,-0.231747,-0.120014,-0.157088,0.050043,-0.136672,0.133468,0.128726,-0.238128,0.090861,-0.285787,0.119657,0.061854,0.091464,0.080133,0.077330,0.060467,0.089992,0.042114,0.110278,0.109572,0.098138,-0.150981
Bilbao_rain_1h,-0.249633,0.259719,1.000000,0.265864,0.069878,0.106765,0.370733,0.085398,0.081131,0.279350,0.069997,-0.030723,0.135524,0.140101,0.052558,0.092984,0.096730,0.052458,0.016392,0.187423,-0.001412,0.008269,-0.147768,-0.120618,-0.054814,-0.095723,-0.206765,-0.210323,-0.298587,-0.135198,-0.127953,-0.604616,-0.170009,-0.103868,-0.116835,-0.157326,-0.148397,-0.138901,-0.141269,-0.182494,-0.106593,-0.219871,-0.120575,-0.135927,-0.116431,-0.152510
Valencia_wind_speed,-0.090161,0.513092,0.265864,1.000000,-0.075227,-0.019388,0.210524,0.386478,0.163675,0.248643,0.347966,-0.066071,0.221887,0.316035,0.031804,0.046085,0.115133,0.050282,0.027637,0.093865,-0.037553,0.058629,-0.099056,-0.037605,-0.096374,-0.069092,-0.041408,-0.024045,-0.158475,0.065815,0.072366,-0.201379,-0.008508,-0.413017,0.075533,-0.040998,-0.021970,-0.021456,-0.010166,-0.022676,0.001413,-0.033271,0.003618,-0.011982,-0.019742,-0.142791
Seville_humidity,-0.079025,-0.117892,0.069878,-0.075227,1.000000,0.799831,0.061680,-0.088180,0.399436,-0.087246,-0.138625,0.164064,0.366602,-0.202449,-0.051022,0.227476,0.023556,0.021599,0.034343,0.164019,0.015555,0.007351,-0.228442,-0.050515,-0.099458,-0.328265,-0.088094,-0.566426,-0.103813,-0.650643,-0.663276,-0.105088,-0.743126,0.464012,-0.657427,-0.606770,-0.708937,-0.617797,-0.605493,-0.604733,-0.595065,-0.583718,-0.784850,-0.717171,-0.688664,-0.167290
Madrid_humidity,-0.103359,-0.137092,0.106765,-0.019388,0.799831,1.000000,0.041878,-0.016808,0.374112,-0.069570,-0.058518,0.183725,0.484293,-0.125680,-0.061265,0.195455,0.031653,0.025198,0.059958,0.250614,0.017797,0.012571,-0.341407,-0.051139,-0.053074,-0.291095,-0.168207,-0.576413,-0.121737,-0.705918,-0.706989,-0.139686,-0.738819,0.378980,-0.689854,-0.691803,-0.803260,-0.684867,-0.635760,-0.634825,-0.636777,-0.611395,-0.769591,-0.802605,-0.759633,-0.150536
Bilbao_clouds_all,-0.068123,0.244001,0.370733,0.210524,0.061680,0.041878,1.000000,0.031915,0.046737,0.280154,0.094019,-0.065120,0.109788,0.075066,0.052913,0.041090,0.080180,0.037506,0.009557,0.089281,-0.041013,0.024339,-0.080837,-0.124169,0.000377,-0.033825,-0.079778,-0.102322,-0.135672,0.002621,-0.000299,-0.536205,-0.095003,-0.129684,-0.003806,-0.034040,-0.048491,-0.023171,-0.067731,-0.114118,-0.010804,-0.158014,-0.077417,-0.046686,-0.046189,-0.127293
Bilbao_wind_speed,0.049197,0.377854,0.085398,0.386478,-0.088180,-0.016808,0.031915,1.000000,0.127344,0.417534,0.275317,-0.018225,0.239326,0.213420,-0.026640,0.073080,-0.001642,0.009572,-0.026037,0.088502,-0.038246,-0.008114,-0.101497,-0.003074,-0.122915,-0.086691,0.054035,0.103342,0.075541,0.091352,0.093919,-0.031661,0.080357,-0.279825,0.093177,0.011151,0.025367,0.018967,0.107302,0.142435,0.023711,0.177123,0.055077,0.031245,0.021425,-0.081602
Seville_clouds_all,-0.140583,0.191251,0.081131,0.163675,0.399436,0.374112,0.046737,0.127344,1.000000,0.053482,0.136591,-0.031373,0.552414,0.144119,0.003590,0.408001,0.001718,0.020264,0.087240,0.295499,0.029194,-0.009782,-0.376157,-0.099166,-0.330575,-0.537924,-0.214600,-0.181783,-0.219365,-0.188804,-0.186982,-0.101888,-0.208859,0.097491,-0.179211,-0.205060,-0.238895,-0.186463,-0.134249,-0.152393,-0.153412,-0.165567,-0.200453,-0.227094,-0.212758,-0.091804
Bilbao_wind_deg,-0.155738,0.270950,0.279350,0.248643,-0.087246,-0.069570,0.280154,0.417534,0.053482,1.000000,0.177393,-0.015481,0.085040,0.120378,0.026187,0.030082,-0.041314,0.034220,0.006888,0.057058,0.007202,-0.022680,-0.036532,-0.053839,-0.107361,-0.008937,-0.124372,-0.076038,-0.166636,0.069642,0.069065,-0.264719,0.005110,-0.230583,0.069433,0.049775,0.028535,0.068701,0.095047,0.065396,0.086482,0.031187,0.062663,0.044102,0.048397,-0.120800
Barcelona_wind_speed,-0.218781,0.294640,0.069997,0.347966,-0.138625,-0.058518,0.094019,0.275317,0.136591,0.177393,1.000000,0.076376,0.147652,0.212193,0.042136,0.105892,0.015752,0.001280,0.058662,0.130751,-0.001722,0.030336,-0.106432,-0.048004,-0.083399,-0.090902,-0.076290,0.152852,-0.020364,0.138254,0.121330,-0.064746,0.147628,-0.249610,0.097663,0.114497,0.084209,0.116240,0.123403,0.120361,0.109268,0.109692,0.130367,0.089365,0.084679,-0.103633
Barcelona_wind_deg,-0.140449,-0.095380,-0.030723,-0.066071,0.164064,0.183725,-0.065120,-0.018225,-0.031373,-0.015481,0.076376,1.000000,-0.041083,-0.098837,-0.037854,-0.101449,-0.023039,-0.001079,-0.043800,-0.112801,-0.011875,-0.021024,0.095456,0.151534,0.123565,0.068195,0.067974,-0.083393,0.093900,-0.170304,-0.201419,0.049678,-0.159882,0.045277,-0.228330,-0.151302,-0.193487,-0.189016,-0.182302,-0.164656,-0.226583,-0.147388,-0.195212,-0.211319,-0.211010,-0.116133
Madrid_clouds_all,-0.116928,0.230126,0.135524,0.221887,0.366602,0.484293,0.109788,0.239326,0.552414,0.085040,0.147652,-0.041083,1.000000,0.168245,0.008570,0.302665,0.041997,0.010833,0.077246,0.402147,-0.000355,0.023323,-0.533331,-0.119970,-0.323787,-0.383770,-0.218671,-0.190138,-0.190070,-0.200774,-0.200355,-0.172030,-0.240838,0.066366,-0.193107,-0.242409,-0.279732,-0.223940,-0.167008,-0.174079,-0.188578,-0.172921,-0.245756,-0.262908,-0.245475,-0.081623
Seville_wind_speed,-0.093926,0.434104,0.140101,0.316035,-0.202449,-0.125680,0.075066,0.213420,0.144119,0.120378,0.212193,-0.098837,0.168245,1.000000,0.074540,0.125560,0.046176,-0.008853,0.001149,0.177805,-0.019804,0.031472,-0.192897,-0.056570,-0.132661,-0.143958,-0.200940,0.096339,-0.136514,0.102171,0.104756,-0.111509,0.139573,-0.217303,0.104281,0.068902,0.100081,0.085395,0.093079,0.082904,0.097407,0.070808,0.154254,0.108460,0.089832,-0.048433
Barcelona_rain_1h,-0.075692,0.062758,0.052558,0.031804,-0.051022,-0.061265,0.052913,-0.026640,0.003590,0.026187,0.042136,-0.037854,0.008570,0.074540,1.000000,0.050899,0.067461,0.053550,-0.012500,0.065321,-0.020084,0.042576,-0.038090,-0.525751,-0.055521,-0.007767,-0.001837,0.064457,-0.016906,0.068789,0.045358,-0.051911,0.069337,0.009027,0.015905,0.083288,0.079558,0.060384,0.031765,0.034889,0.023582,0.032362,0.065312,0.075013,0.070146,-0.056633
Seville_rain_1h,-0.075340,0.108413,0.092984,0.046085,0.227476,0.195455,0.041090,0.073080,0.408001,0.030082,0.105892,-0.101449,0.302665,0.125560,0.050899,1.000000,-0.004686,0.003875,-0.007996,0.343525,0.007454,-0.003883,-0.339384,-0.159181,-0.168369,-0.693443,-0.086235,-0.094417,-0.066794,-0.116127,-0.112932,-0.074103,-0.113766,0.093558,-0.106177,-0.110305,-0.125740,-0.098982,-0.072453,-0.080749,-0.078631,-0.085650,-0.113038,-0.115727,-0.101189,-0.031572
Bilbao_snow_3h,-0.092377,0.071183,0.096730,0.115133,0.023556,0.031653,0.080180,-0.001642,0.001718,-0.041314,0.015752,-0.023039,0.041997,0.046176,0.067461,-0.004686,1.000000,-0.001539,-0.000391,0.030993,0.002985,0.390939,0.000365,-0.033598,-0.023428,0.011493,-0.041579,-0.107188,-0.140297,-0.093042,-0.092345,-0.107220,-0.094889,-0.048367,-0.089771,-0.087943,-0.084406,-0.086561,-0.086115,-0.096477,-0.079382,-0.105006,-0.075545,-0.081209,-0.074892,-0.031721
Barcelona_pressure,-0.040157,0.011134,0.052458,0.050282,0.021599,0.025198,0.037506,0.009572,0.020264,0.034220,0.001280,-0.001079,0.010833,-0.008853,0.053550,0.003875,-0.001539,1.000000,-0.001685,-0.003937,-0.002796,-0.000473,0.004365,-0.013790,-0.014092,-0.014359,-0.007790,-0.047179,-0.091181,-0.029292,-0.028260,-0.048567,-0.041542,-0.003012,-0.026596,-0.034412,-0.015984,-0.033221,-0.022514,-0.027410,-0.029612,-0.031854,-0.032889,-0.017886,-0.017819,-0.034385
Seville_rain_3h,-0.082525,0.004795,0.016392,0.027637,0.034343,0.059958,0.009557,-0.026037,0.087240,0.006888,0.058662,-0.043800,0.077246,0.001149,-0.012500,-0.007996,-0.000391,-0.001685,1.000000,0.074880,0.145740,-0.001147,-0.129439,0.023488,0.011756,0.009732,0.017486,-0.067920,0.019942,-0.064900,-0.062605,-0.052032,-0.051013,0.031254,-0.059002,-0.049273,-0.048765,-0.041804,-0.021331,-0.032691,-0.029569,-0.043441,-0.032983,-0.043338,-0.035708,-0.032945
Madrid_rain_1h,-0.068980,0.150446,0.187423,0.093865,0.164019,0.250614,0.089281,0.088502,0.295499,0.057058,0.130751,-0.112801,0.402147,0.177805,0.065321,0.343525,0.030993,-0.003937,0.074880,1.000000,0.018953,-0.004290,-0.718816,-0.144551,-0.199285,-0.365701,-0.136173,-0.085614,-0.081161,-0.078935,-0.073005,-0.158555,-0.090787,0.073589,-0.064249,-0.072734,-0.116052,-0.054825,-0.041161,-0.055851,-0.028900,-0.068176,-0.081794,-0.105667,-0.094601,-0.027159
Barcelona_rain_3h,-0.104326,-0.014644,-0.001412,-0.037553,0.015555,0.017797,-0.041013,-0.038246,0.029194,0.007202,-0.001722,-0.011875,-0.000355,-0.019804,-0.020084,0.007454,0.002985,-0.002796,0.145740,0.018953,1.000000,-0.001905,-0.006607,0.026554,0.025215,-0.017497,0.030491,-0.070069,0.036706,-0.061068,-0.058942,-0.002715,-0.039126,0.002920,-0.055676,-0.051365,-0.046967,-0.042970,-0.027060,-0.043223,-0.029398,-0.059089,-0.012016,-0.039565,-0.029094,-0.024720
Valencia_snow_3h,-0.028130,0.021660,0.008269,0.058629,0.007351,0.012571,0.024339,-0.008114,-0.009782,-0.022680,0.030336,-0.021024,0.023323,0.031472,0.042576,-0.003883,0.390939,-0.000473,-0.001147,-0.004290,-0.001905,1.000000,0.006523,-0.005456,-0.014354,0.006099,-0.027016,-0.029561,-0.050974,-0.027693,-0.027452,-0.033581,-0.025473,-0.019085,-0.026649,-0.029249,-0.024737,-0.029135,-0.028634,-0.031726,-0.027172,-0.034205,-0.019706,-0.023734,-0.021807,-0.021633
Madrid_weather_id,0.047202,-0.169358,-0.147768,-0.099056,-0.228442,-0.341407,-0.080837,-0.101497,-0.376157,-0.036532,-0.106432,0.095456,-0.533331,-0.192897,-0.038090,-0.339384,0.000365,0.004365,-0.129439,-0.718816,-0.006607,0.006523,1.000000,0.137262,0.245081,0.401143,0.155108,0.103614,0.098011,0.103162,0.095043,0.160212,0.116834,-0.097104,0.083657,0.105912,0.149340,0.085587,0.056109,0.068572,0.056176,0.076601,0.110713,0.136829,0.123498,0.030868
Barcelona_weather_id,0.034761,-0.099582,-0.120618,-0.037605,-0.050515,-0.051139,-0.124169,-0.003074,-0.099166,-0.053839,-0.048004,0.151534,-0.119970,-0.056570,-0.525751,-0.159181,-0.033598,-0.013790,0.023488,-0.144551,0.026554,-0.005456,0.137262,1.000000,0.128763,0.123593,0.068283,-0.000401,0.031370,0.017432,0.031316,0.119813,0.014065,-0.096343,0.046090,0.018332,0.027375,0.029239,0.053279,0.053303,0.046167,0.054720,0.020735,0.025671,0.026252,0.063868
Bilbao_pressure,-0.022475,-0.231747,-0.054814,-0.096374,-0.099458,-0.053074,0.000377,-0.122915,-0.330575,-0.107361,-0.083399,0.123565,-0.323787,-0.132661,-0.055521,-0.168369,-0.023428,-0.014092,0.011756,-0.199285,0.025215,-0.014354,0.245081,0.128763,1.000000,0.193543,0.534284,-0.054399,0.434461,-0.186278,-0.174843,0.060315,-0.114349,-0.028138,-0.157873,-0.217623,-0.139887,-0.229760,-0.267415,-0.250325,-0.230942,-0.221529,-0.150221,-0.156223,-0.160023,0.039052
Seville_weather_id,0.072472,-0.120014,-0.095723,-0.069092,-0.328265,-0.291095,-0.033825,-0.086691,-0.537924,-0.008937,-0.090902,0.068195,-0.383770,-0.143958,-0.007767,-0.693443,0.011493,-0.014359,0.009732,-0.365701,-0.017497,0.006099,0.401143,0.123593,0.193543,1.000000,0.090076,0.117190,0.065481,0.171346,0.170912,0.074054,0.166098,-0.132907,0.166209,0.176048,0.193848,0.168608,0.130659,0.134535,0.150195,0.132564,0.180721,0.185768,0.174238,0.061104
Valencia_pressure,0.267772,-0.157088,-0.206765,-0.041408,-0.088094,-0.168207,-0.079778,0.054035,-0.214600,-0.124372,-0.076290,0.067974,-0.218671,-0.200940,-0.001837,-0.086235,-0.041579,-0.007790,0.017486,-0.136173,0.030491,-0.027016,0.155108,0.068283,0.534284,0.090076,1.000000,0.225118,0.799272,0.114845,0.087385,0.212183,0.121508,-0.021253,0.055783,0.099545,0.123501,0.026211,0.001008,0.074986,-0.067132,0.147187,0.027998,0.082532,0.035991,0.086022
Seville_temp_max,0.039424,0.050043,-0.210323,-0.024045,-0.566426,-0.576413,-0.102322,0.103342,-0.181783,-0.076038,0.152852,-0.083393,-0.190138,0.096339,0.064457,-0.094417,-0.107188,-0.047179,-0.067920,-0.085614,-0.070069,-0.029561,0.103614,-0.000401,-0.054399,0.117190,0.225118,1.000000,0.279308,0.771964,0.745269,0.221179,0.907261,-0.214801,0.694121,0.738489,0.772369,0.693193,0.651814,0.703218,0.586923,0.726510,0.743801,0.740831,0.674561,0.109834
Madrid_pressure,0.385578,-0.136672,-0.298587,-0.158475,-0.103813,-0.121737,-0.135672,0.075541,-0.219365,-0.166636,-0.020364,0.093900,-0.190070,-0.136514,-0.016906,-0.066794,-0.140297,-0.091181,0.019942,-0.081161,0.036706,-0.050974,0.098011,0.031370,0.434461,0.065481,0.799272,0.279308,1.000000,0.114278,0.088261,0.255825,0.150050,0.014234,0.059584,0.072290,0.092253,0.010542,0.009734,0.092394,-0.068083,0.176838,0.037876,0.054819,0.014089,0.092638
Valencia_temp_max,0.087002,0.133468,-0.135198,0.065815,-0.650643,-0.705918,0.002621,0.091352,-0.188804,0.069642,0.138254,-0.170304,-0.200774,0.102171,0.068789,-0.116127,-0.093042,-0.029292,-0.064900,-0.078935,-0.061068,-0.027693,0.103162,0.017432,-0.186278,0.171346,0.114845,0.771964,0.114278,1.000000,0.987533,0.112775,0.896059,-0.399380,0.949377,0.918256,0.917838,0.912094,0.840573,0.854592,0.845057,0.837574,0.886449,0.911331,0.862683,0.144270
Valencia_temp,0.135294,0.128726,-0.127953,0.072366,-0.663276,-0.706989,-0.000299,0.093919,-0.186982,0.069065,0.121330,-0.201419,-0.200355,0.104756,0.045358,-0.112932,-0.092345,-0.028260,-0.062605,-0.073005,-0.058942,-0.027452,0.095043,0.031316,-0.174843,0.170912,0.087385,0.745269,0.088261,0.987533,1.000000,0.106095,0.887040,-0.413654,0.985479,0.901400,0.917820,0.914601,0.847584,0.854892,0.874447,0.833562,0.890915,0.915753,0.871563,0.173225
Bilbao_weather_id,0.192485,-0.238128,-0.604616,-0.201379,-0.105088,-0.139686,-0.536205,-0.031661,-0.101888,-0.264719,-0.064746,0.049678,-0.172030,-0.111509,-0.051911,-0.074103,-0.107220,-0.048567,-0.052032,-0.158555,-0.002715,-0.033581,0.160212,0.119813,0.060315,0.074054,0.212183,0.221179,0.255825,0.112775,0.106095,1.000000,0.190360,0.114838,0.095554,0.146071,0.153665,0.128188,0.140580,0.190635,0.098428,0.235183,0.145173,0.143126,0.124199,0.145875
Seville_temp,0.042897,0.090861,-0.170009,-0.008508,-0.743126,-0.738819,-0.095003,0.080357,-0.208859,0.005110,0.147628,-0.159882,-0.240838,0.139573,0.069337,-0.113766,-0.094889,-0.041542,-0.051013,-0.090787,-0.039126,-0.025473,0.116834,0.014065,-0.114349,0.166098,0.121508,0.907261,0.150050,0.896059,0.887040,0.190360,1.000000,-0.281993,0.852492,0.866389,0.920908,0.852651,0.818454,0.839014,0.779252,0.828099,0.955160,0.917075,0.868453,0.159343
Valencia_humidity,0.023917,-0.285787,-0.103868,-0.413017,0.464012,0.378980,-0.129684,-0.279825,0.097491,-0.230583,-0.249610,0.045277,0.066366,-0.217303,0.009027,0.093558,-0.048367,-0.003012,0.031254,0.073589,0.002920,-0.019085,-0.097104,-0.096343,-0.028138,-0.132907,-0.021253,-0.214801,0.014234,-0.399380,-0.413654,0.114838,-0.281993,1.000000,-0.413537,-0.221430,-0.262919,-0.247168,-0.271621,-0.260946,-0.266820,-0.241397,-0.301694,-0.261356,-0.247574,0.043140
Valencia_temp_min,0.185468,0.119657,-0.116835,0.075533,-0.657427,-0.689854,-0.003806,0.093177,-0.179211,0.069433,0.097663,-0.228330,-0.193107,0.104281,0.015905,-0.106177,-0.089771,-0.026596,-0.059002,-0.064249,-0.055676,-0.026649,0.083657,0.046090,-0.157873,0.166209,0.055783,0.694121,0.059584,0.949377,0.985479,0.095554,0.852492,-0.413537,1.000000,0.860510,0.893368,0.892024,0.832773,0.832393,0.879687,0.806606,0.871738,0.897012,0.860347,0.201863
Barcelona_temp_max,0.047417,0.061854,-0.157326,-0.040998,-0.606770,-0.691803,-0.034040,0.011151,-0.205060,0.049775,0.114497,-0.151302,-0.242409,0.068902,0.083288,-0.110305,-0.087943,-0.034412,-0.049273,-0.072734,-0.051365,-0.029249,0.105912,0.018332,-0.217623,0.176048,0.099545,0.738489,0.072290,0.918256,0.901400,0.146071,0.866389,-0.221430,0.860510,1.000000,0.906248,0.974480,0.854620,0.867268,0.885911,0.844563,0.862597,0.896766,0.847888,0.164734
Madrid_temp_max,0.093378,0.091464,-0.148397,-0.021970,-0.708937,-0.803260,-0.048491,0.025367,-0.238895,0.028535,0.084209,-0.193487,-0.279732,0.100081,0.079558,-0.125740,-0.084406,-0.015984,-0.048765,-0.116052,-0.046967,-0.024737,0.149340,0.027375,-0.139887,0.193848,0.123501,0.772369,0.092253,0.917838,0.917820,0.153665,0.920908,-0.262919,0.893368,0.906248,1.000000,0.900428,0.865596,0.872234,0.836680,0.846887,0.923481,0.988871,0.939147,0.182548
Barcelona_temp,0.068078,0.080133,-0.138901,-0.021456,-0.617797,-0.684867,-0.023171,0.018967,-0.186463,0.068701,0.116240,-0.189016,-0.223940,0.085395,0.060384,-0.098982,-0.086561,-0.033221,-0.041804,-0.054825,-0.042970,-0.029135,0.085587,0.029239,-0.229760,0.168608,0.026211,0.693193,0.010542,0.912094,0.914601,0.128188,0.852651,-0.247168,0.892024,0.974480,0.900428,1.000000,0.867434,0.865705,0.964089,0.831470,0.873170,0.903143,0.868222,0.182673
Bilbao_temp_min,0.028698,0.077330,-0.141269,-0.010166,-0.605493,-0.635760,-0.067731,0.107302,-0.134249,0.095047,0.123403,-0.182302,-0.167008,0.093079,0.031765,-0.072453,-0.086115,-0.022514,-0.021331,-0.041161,-0.027060,-0.028634,0.056109,0.053279,-0.267415,0.130659,0.001008,0.651814,0.009734,0.840573,0.847584,0.140580,0.818454,-0.271621,0.832773,0.854620,0.865596,0.867434,1.000000,0.982936,0.831224,0.932219,0.847007,0.876185,0.845799,0.172920
Bilbao_temp,0.081799,0.060467,-0.182494,-0.022676,-0.604733,-0.634825,-0.114118,0.142435,-0.152393,0.065396,0.120361,-0.164656,-0.174079,0.082904,0.034889,-0.080749,-0.096477,-0.027410,-0.032691,-0.055851,-0.043223,-0.031726,0.068572,0.053303,-0.250325,0.134535,0.074986,0.703218,0.092394,0.854592,0.854892,0.190635,0.839014,-0.260946,0.832393,0.867268,0.872234,0.865705,0.982936,1.000000,0.810785,0.981624,0.842972,0.875271,0.838195,0.176411
Barcelona_temp_min,0.103436,0.089992,-0.106593,0.001413,-0.595065,-0.636777,-0.010804,0.023711,-0.153412,0.086482,0.109268,-0.226583,-0.188578,0.097407,0.023582,-0.078631,-0.079382,-0.029612,-0.029569,-0.028900,-0.029398,-0.027172,0.056176,0.046167,-0.230942,0.150195,-0.067132,0.586923,-0.068083,0.845057,0.874447,0.098428,0.779252,-0.266820,0.879687,0.885911,0.836680,0.964089,0.831224,0.810785,1.000000,0.764031,0.831689,0.853881,0.838985,0.195984
Bilbao_temp_max,0.146216,0.042114,-0.219871,-0.033271,-0.583718,-0.611395,-0.158014,0.177123,-0.165567,0.031187,0.109692,-0.147388,-0.172921,0.070808,0.032362,-0.085650,-0.105006,-0.031854,-0.043441,-0.068176,-0.059089,-0.034205,0.076601,0.054720,-0.221529,0.132564,0.147187,0.726510,0.176838,0.837574,0.833562,0.235183,0.828099,-0.241397,0.806606,0.844563,0.846887,0.831470,0.932219,0.981624,0.764031,1.000000,0.808278,0.843633,0.802041,0.180934

In [404]:
# have a look at feature distributions
train0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8763 entries, 0 to 8762
Data columns (total 49 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            8763 non-null   int64
 1   time                  8763 non-null   object
 2   Madrid_wind_speed     8763 non-null   float64
 3   Valencia_wind_deg     8763 non-null   object
 4   Bilbao_rain_1h        8763 non-null   float64
 5   Valencia_wind_speed   8763 non-null   float64
 6   Seville_humidity      8763 non-null   float64
 7   Madrid_humidity       8763 non-null   float64
 8   Bilbao_clouds_all     8763 non-null   float64
 9   Bilbao_wind_speed     8763 non-null   float64
 10  Seville_clouds_all    8763 non-null   float64
 11  Bilbao_wind_deg       8763 non-null   float64
 12  Barcelona_wind_speed  8763 non-null   float64
 13  Barcelona_wind_deg    8763 non-null   float64
 14  Madrid_clouds_all     8763 non-null   float64
 15  Seville_wind_speed    8763 non-null   float64
 16  Barcelona_rain_1h     8763 non-null   float64
 17  Seville_pressure      8763 non-null   object
 18  Seville_rain_1h       8763 non-null   float64
 19  Bilbao_snow_3h        8763 non-null   float64
 20  Barcelona_pressure    8763 non-null   float64
 21  Seville_rain_3h       8763 non-null   float64
 22  Madrid_rain_1h        8763 non-null   float64
 23  Barcelona_rain_3h     8763 non-null   float64
 24  Valencia_snow_3h      8763 non-null   float64
 25  Madrid_weather_id     8763 non-null   float64
 26  Barcelona_weather_id  8763 non-null   float64
 27  Bilbao_pressure       8763 non-null   float64
 28  Seville_weather_id    8763 non-null   float64
 29  Valencia_pressure     6695 non-null   float64
 30  Seville_temp_max      8763 non-null   float64
 31  Madrid_pressure       8763 non-null   float64
 32  Valencia_temp_max     8763 non-null   float64
 33  Valencia_temp         8763 non-null   float64
 34  Bilbao_weather_id     8763 non-null   float64
 35  Seville_temp          8763 non-null   float64
 36  Valencia_humidity     8763 non-null   float64
 37  Valencia_temp_min     8763 non-null   float64
 38  Barcelona_temp_max    8763 non-null   float64
 39  Madrid_temp_max       8763 non-null   float64
 40  Barcelona_temp        8763 non-null   float64
 41  Bilbao_temp_min       8763 non-null   float64
 42  Bilbao_temp           8763 non-null   float64
 43  Barcelona_temp_min    8763 non-null   float64
 44  Bilbao_temp_max       8763 non-null   float64
 45  Seville_temp_min      8763 non-null   float64
 46  Madrid_temp           8763 non-null   float64
 47  Madrid_temp_min       8763 non-null   float64
 48  load_shortfall_3h     8763 non-null   float64
dtypes: float64(45), int64(1), object(3)
memory usage: 3.3+ MB

In [405]:
train0.Valencia_snow_3h = train0.Valencia_snow_3h.astype(np.int64)
train0.Bilbao_snow_3h = train0.Bilbao_snow_3h.astype(np.int64)

In [406]:
train0['time'] = pd.to_datetime(train0['time'])

In [407]:
train0.isnull().sum()

Unnamed: 0                 0
time                       0
Madrid_wind_speed          0
Valencia_wind_deg          0
Bilbao_rain_1h             0
Valencia_wind_speed        0
Seville_humidity           0
Madrid_humidity            0
Bilbao_clouds_all          0
Bilbao_wind_speed          0
Seville_clouds_all         0
Bilbao_wind_deg            0
Barcelona_wind_speed       0
Barcelona_wind_deg         0
Madrid_clouds_all          0
Seville_wind_speed         0
Barcelona_rain_1h          0
Seville_pressure           0
Seville_rain_1h            0
Bilbao_snow_3h             0
Barcelona_pressure         0
Seville_rain_3h            0
Madrid_rain_1h             0
Barcelona_rain_3h          0
Valencia_snow_3h           0
Madrid_weather_id          0
Barcelona_weather_id       0
Bilbao_pressure            0
Seville_weather_id         0
Valencia_pressure       2068
Seville_temp_max           0
Madrid_pressure            0
Valencia_temp_max          0
Valencia_temp              0
Bilbao_weather_id          0
Seville_temp               0
Valencia_humidity          0
Valencia_temp_min          0
Barcelona_temp_max         0
Madrid_temp_max            0
Barcelona_temp             0
Bilbao_temp_min            0
Bilbao_temp                0
Barcelona_temp_min         0
Bilbao_temp_max            0
Seville_temp_min           0
Madrid_temp                0
Madrid_temp_min            0
load_shortfall_3h          0
dtype: int64

In [408]:
train0.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8763 entries, 0 to 8762
Data columns (total 49 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Unnamed: 0            8763 non-null   int64
 1   time                  8763 non-null   datetime64[ns]
 2   Madrid_wind_speed     8763 non-null   float64
 3   Valencia_wind_deg     8763 non-null   object
 4   Bilbao_rain_1h        8763 non-null   float64
 5   Valencia_wind_speed   8763 non-null   float64
 6   Seville_humidity      8763 non-null   float64
 7   Madrid_humidity       8763 non-null   float64
 8   Bilbao_clouds_all     8763 non-null   float64
 9   Bilbao_wind_speed     8763 non-null   float64
 10  Seville_clouds_all    8763 non-null   float64
 11  Bilbao_wind_deg       8763 non-null   float64
 12  Barcelona_wind_speed  8763 non-null   float64
 13  Barcelona_wind_deg    8763 non-null   float64
 14  Madrid_clouds_all     8763 non-null   float64
 15  Seville_wind_speed    8763 non-null   float64
 16  Barcelona_rain_1h     8763 non-null   float64
 17  Seville_pressure      8763 non-null   object
 18  Seville_rain_1h       8763 non-null   float64
 19  Bilbao_snow_3h        8763 non-null   int64
 20  Barcelona_pressure    8763 non-null   float64
 21  Seville_rain_3h       8763 non-null   float64
 22  Madrid_rain_1h        8763 non-null   float64
 23  Barcelona_rain_3h     8763 non-null   float64
 24  Valencia_snow_3h      8763 non-null   int64
 25  Madrid_weather_id     8763 non-null   float64
 26  Barcelona_weather_id  8763 non-null   float64
 27  Bilbao_pressure       8763 non-null   float64
 28  Seville_weather_id    8763 non-null   float64
 29  Valencia_pressure     6695 non-null   float64
 30  Seville_temp_max      8763 non-null   float64
 31  Madrid_pressure       8763 non-null   float64
 32  Valencia_temp_max     8763 non-null   float64
 33  Valencia_temp         8763 non-null   float64
 34  Bilbao_weather_id     8763 non-null   float64
 35  Seville_temp          8763 non-null   float64
 36  Valencia_humidity     8763 non-null   float64
 37  Valencia_temp_min     8763 non-null   float64
 38  Barcelona_temp_max    8763 non-null   float64
 39  Madrid_temp_max       8763 non-null   float64
 40  Barcelona_temp        8763 non-null   float64
 41  Bilbao_temp_min       8763 non-null   float64
 42  Bilbao_temp           8763 non-null   float64
 43  Barcelona_temp_min    8763 non-null   float64
 44  Bilbao_temp_max       8763 non-null   float64
 45  Seville_temp_min      8763 non-null   float64
 46  Madrid_temp           8763 non-null   float64
 47  Madrid_temp_min       8763 non-null   float64
 48  load_shortfall_3h     8763 non-null   float64
dtypes: datetime64[ns](1), float64(43), int64(3), object(2)
memory usage: 3.3+ MB

In [409]:
test0.isnull().sum()

Unnamed: 0                0
time                      0
Madrid_wind_speed         0
Valencia_wind_deg         0
Bilbao_rain_1h            0
Valencia_wind_speed       0
Seville_humidity          0
Madrid_humidity           0
Bilbao_clouds_all         0
Bilbao_wind_speed         0
Seville_clouds_all        0
Bilbao_wind_deg           0
Barcelona_wind_speed      0
Barcelona_wind_deg        0
Madrid_clouds_all         0
Seville_wind_speed        0
Barcelona_rain_1h         0
Seville_pressure          0
Seville_rain_1h           0
Bilbao_snow_3h            0
Barcelona_pressure        0
Seville_rain_3h           0
Madrid_rain_1h            0
Barcelona_rain_3h         0
Valencia_snow_3h          0
Madrid_weather_id         0
Barcelona_weather_id      0
Bilbao_pressure           0
Seville_weather_id        0
Valencia_pressure       454
Seville_temp_max          0
Madrid_pressure           0
Valencia_temp_max         0
Valencia_temp             0
Bilbao_weather_id         0
Seville_temp              0
Valencia_humidity         0
Valencia_temp_min         0
Barcelona_temp_max        0
Madrid_temp_max           0
Barcelona_temp            0
Bilbao_temp_min           0
Bilbao_temp               0
Barcelona_temp_min        0
Bilbao_temp_max           0
Seville_temp_min          0
Madrid_temp               0
Madrid_temp_min           0
dtype: int64

<a id="four"></a>
## 4. Data Engineering
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Data engineering ⚡ |
| :--------------------------- |
| In this section you are required to: clean the dataset, and possibly create new features - as identified in the EDA phase. |

---

In [410]:
# remove missing values/ features
target= train0['load_shortfall_3h']
test_time= test0['time']

train1= train0.drop(['time', 'load_shortfall_3h'], axis=1)
test1= test0.drop('time', axis=1)

data1= pd.concat([train1, test1], axis=0).reset_index(drop=True)
data1

,Unnamed: 0,Madrid_wind_speed,Valencia_wind_deg,Bilbao_rain_1h,Valencia_wind_speed,Seville_humidity,Madrid_humidity,Bilbao_clouds_all,Bilbao_wind_speed,Seville_clouds_all,Bilbao_wind_deg,Barcelona_wind_speed,Barcelona_wind_deg,Madrid_clouds_all,Seville_wind_speed,Barcelona_rain_1h,Seville_pressure,Seville_rain_1h,Bilbao_snow_3h,Barcelona_pressure,Seville_rain_3h,Madrid_rain_1h,Barcelona_rain_3h,Valencia_snow_3h,Madrid_weather_id,Barcelona_weather_id,Bilbao_pressure,Seville_weather_id,Valencia_pressure,Seville_temp_max,Madrid_pressure,Valencia_temp_max,Valencia_temp,Bilbao_weather_id,Seville_temp,Valencia_humidity,Valencia_temp_min,Barcelona_temp_max,Madrid_temp_max,Barcelona_temp,Bilbao_temp_min,Bilbao_temp,Barcelona_temp_min,Bilbao_temp_max,Seville_temp_min,Madrid_temp,Madrid_temp_min
0,0,0.666667,level_5,0.0,0.666667,74.333333,64.000000,0.000000,1.000000,0.0,223.333333,6.333333,42.666667,0.0,3.333333,0.0,sp25,0.0,0,1036.333333,0.0,0.0,0.0,0,800.0,800.0,1035.000000,800.0,1002.666667,274.254667,971.333333,269.888000,269.888000,800.000000,274.254667,75.666667,269.888000,281.013000,265.938000,281.013000,269.338615,269.338615,281.013000,269.338615,274.254667,265.938000,265.938000
1,1,0.333333,level_10,0.0,1.666667,78.333333,64.666667,0.000000,1.000000,0.0,221.000000,4.000000,139.000000,0.0,3.333333,0.0,sp25,0.0,0,1037.333333,0.0,0.0,0.0,0,800.0,800.0,1035.666667,800.0,1004.333333,274.945000,972.666667,271.728333,271.728333,800.000000,274.945000,71.000000,271.728333,280.561667,266.386667,280.561667,270.376000,270.376000,280.561667,270.376000,274.945000,266.386667,266.386667
2,2,1.000000,level_9,0.0,1.000000,71.333333,64.333333,0.000000,1.000000,0.0,214.333333,2.000000,326.000000,0.0,2.666667,0.0,sp25,0.0,0,1038.000000,0.0,0.0,0.0,0,800.0,800.0,1036.000000,800.0,1005.333333,278.792000,974.000000,278.008667,278.008667,800.000000,278.792000,65.666667,278.008667,281.583667,272.708667,281.583667,275.027229,275.027229,281.583667,275.027229,278.792000,272.708667,272.708667
3,3,1.000000,level_8,0.0,1.000000,65.333333,56.333333,0.000000,1.000000,0.0,199.666667,2.333333,273.000000,0.0,4.000000,0.0,sp25,0.0,0,1037.000000,0.0,0.0,0.0,0,800.0,800.0,1036.000000,800.0,1009.000000,285.394000,994.666667,284.899552,284.899552,800.000000,285.394000,54.000000,284.899552,283.434104,281.895219,283.434104,281.135063,281.135063,283.434104,281.135063,285.394000,281.895219,281.895219
4,4,1.000000,level_7,0.0,1.000000,59.000000,57.000000,2.000000,0.333333,0.0,185.000000,4.333333,260.000000,0.0,3.000000,0.0,sp25,0.0,0,1035.000000,0.0,0.0,0.0,0,800.0,800.0,1035.333333,800.0,NaN,285.513719,1035.333333,283.015115,283.015115,800.000000,285.513719,58.333333,283.015115,284.213167,280.678437,284.213167,282.252063,282.252063,284.213167,282.252063,285.513719,280.678437,280.678437
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11678,11678,0.333333,level_9,0.0,2.000000,81.666667,49.666667,80.000000,1.333333,0.0,70.000000,6.333333,320.000000,0.0,2.000000,0.0,sp24,0.0,0,1029.666667,0.0,0.0,0.0,0,800.0,800.0,1034.666667,800.0,NaN,280.816667,1031.666667,279.816667,279.323333,734.333333,280.210000,69.666667,278.816667,279.816667,281.483333,278.140000,270.816667,273.210000,276.483333,276.150000,279.816667,274.910000,271.150000
11679,11679,0.333333,level_8,0.0,1.333333,61.000000,28.333333,56.666667,1.000000,0.0,36.666667,2.666667,293.333333,0.0,4.000000,0.0,sp24,0.0,0,1028.666667,0.0,0.0,0.0,0,800.0,800.0,1034.333333,800.0,NaN,287.483333,1031.333333,290.816667,290.323333,747.666667,287.280000,32.000000,289.816667,286.483333,287.816667,286.150000,278.150000,278.443333,285.816667,278.816667,287.150000,283.156667,280.483333
11680,11680,1.000000,level_6,0.0,3.000000,47.000000,26.333333,0.000000,0.666667,0.0,14.666667,2.666667,233.333333,0.0,4.666667,0.0,sp23,0.0,0,1027.000000,0.0,0.0,0.0,0,800.0,800.0,1033.000000,800.0,NaN,290.816667,1030.000000,293.483333,293.483333,800.000000,290.816667,23.666667,293.483333,289.483333,288.816667,288.820000,284.150000,285.073333,288.150000,285.816667,290.816667,287.733333,286.483333
11681,11681,1.000000,level_6,0.0,2.000000,52.666667,56.666667,0.000000,0.666667,0.0,19.000000,2.333333,253.333333,0.0,3.333333,0.0,sp23,0.0,0,1027.000000,0.0,0.0,0.0,0,800.0,800.0,1033.333333,800.0,NaN,288.816667,1030.333333,286.483333,285.976667,800.000000,288.300000,59.000000,285.483333,285.816667,285.150000,284.473333,280.150000,281.626667,283.150000,282.816667,287.483333,283.813333,282.150000
11682,11682,1.333333,level_10,0.0,2.333333,61.666667,69.333333,0.000000,1.333333,0.0,120.000000,4.666667,310.000000,0.0,3.666667,0.0,sp23,0.0,0,1028.000000,0.0,0.0,0.0,0,800.0,800.0,1034.000000,800.0,NaN,284.816667,1030.666667,281.150000,280.313333,800.000000,284.423333,79.000000,279.483333,283.816667,276.816667,281.133333,276.150000,276.450000,278.483333,276.816667,283.816667,276.623333,276.483333

In [411]:
data1.drop(['Unnamed: 0'], axis=1, inplace=True)
data1.drop(['Valencia_wind_deg'], axis=1 , inplace=True)
data1.drop(['Seville_pressure'], axis=1, inplace=True)

In [412]:
# create new features
target.isna().sum()

0

In [413]:
test_time.isna().sum()

0

In [414]:
# engineer existing features
data1.select_dtypes(np.number).head()

,Madrid_wind_speed,Bilbao_rain_1h,Valencia_wind_speed,Seville_humidity,Madrid_humidity,Bilbao_clouds_all,Bilbao_wind_speed,Seville_clouds_all,Bilbao_wind_deg,Barcelona_wind_speed,Barcelona_wind_deg,Madrid_clouds_all,Seville_wind_speed,Barcelona_rain_1h,Seville_rain_1h,Bilbao_snow_3h,Barcelona_pressure,Seville_rain_3h,Madrid_rain_1h,Barcelona_rain_3h,Valencia_snow_3h,Madrid_weather_id,Barcelona_weather_id,Bilbao_pressure,Seville_weather_id,Valencia_pressure,Seville_temp_max,Madrid_pressure,Valencia_temp_max,Valencia_temp,Bilbao_weather_id,Seville_temp,Valencia_humidity,Valencia_temp_min,Barcelona_temp_max,Madrid_temp_max,Barcelona_temp,Bilbao_temp_min,Bilbao_temp,Barcelona_temp_min,Bilbao_temp_max,Seville_temp_min,Madrid_temp,Madrid_temp_min
0,0.666667,0.0,0.666667,74.333333,64.000000,0.0,1.000000,0.0,223.333333,6.333333,42.666667,0.0,3.333333,0.0,0.0,0,1036.333333,0.0,0.0,0.0,0,800.0,800.0,1035.000000,800.0,1002.666667,274.254667,971.333333,269.888000,269.888000,800.0,274.254667,75.666667,269.888000,281.013000,265.938000,281.013000,269.338615,269.338615,281.013000,269.338615,274.254667,265.938000,265.938000
1,0.333333,0.0,1.666667,78.333333,64.666667,0.0,1.000000,0.0,221.000000,4.000000,139.000000,0.0,3.333333,0.0,0.0,0,1037.333333,0.0,0.0,0.0,0,800.0,800.0,1035.666667,800.0,1004.333333,274.945000,972.666667,271.728333,271.728333,800.0,274.945000,71.000000,271.728333,280.561667,266.386667,280.561667,270.376000,270.376000,280.561667,270.376000,274.945000,266.386667,266.386667
2,1.000000,0.0,1.000000,71.333333,64.333333,0.0,1.000000,0.0,214.333333,2.000000,326.000000,0.0,2.666667,0.0,0.0,0,1038.000000,0.0,0.0,0.0,0,800.0,800.0,1036.000000,800.0,1005.333333,278.792000,974.000000,278.008667,278.008667,800.0,278.792000,65.666667,278.008667,281.583667,272.708667,281.583667,275.027229,275.027229,281.583667,275.027229,278.792000,272.708667,272.708667
3,1.000000,0.0,1.000000,65.333333,56.333333,0.0,1.000000,0.0,199.666667,2.333333,273.000000,0.0,4.000000,0.0,0.0,0,1037.000000,0.0,0.0,0.0,0,800.0,800.0,1036.000000,800.0,1009.000000,285.394000,994.666667,284.899552,284.899552,800.0,285.394000,54.000000,284.899552,283.434104,281.895219,283.434104,281.135063,281.135063,283.434104,281.135063,285.394000,281.895219,281.895219
4,1.000000,0.0,1.000000,59.000000,57.000000,2.0,0.333333,0.0,185.000000,4.333333,260.000000,0.0,3.000000,0.0,0.0,0,1035.000000,0.0,0.0,0.0,0,800.0,800.0,1035.333333,800.0,NaN,285.513719,1035.333333,283.015115,283.015115,800.0,285.513719,58.333333,283.015115,284.213167,280.678437,284.213167,282.252063,282.252063,284.213167,282.252063,285.513719,280.678437,280.678437

In [415]:
### impute using the column mean
for column in [ 
    
]:
    
    data1[column]= data1[column].fillna(None)
    
### impute using the column mode
for column in [
    
]:
    
    data1[column]= data1[column].fillna(data1[column].mode()[0])

In [416]:
data1.loc[:, data1.isna().sum()>0].head()

   Valencia_pressure
0        1002.666667
1        1004.333333
2        1005.333333
3        1009.000000
4                NaN

In [417]:
data1.loc[:, data1.isna().sum()>0].columns

Index(['Valencia_pressure'], dtype='object')

In [418]:
data1.select_dtypes('object').loc[:, data1.isna().sum()>0].columns

Index([], dtype='object')

In [419]:
data1.select_dtypes(np.number).isna().sum().sum()

2522

In [420]:
data2= data1.copy()

In [421]:
from sklearn.neighbors import KNeighborsRegressor

In [422]:
data2.select_dtypes(np.number).isna().sum()

Madrid_wind_speed          0
Bilbao_rain_1h             0
Valencia_wind_speed        0
Seville_humidity           0
Madrid_humidity            0
Bilbao_clouds_all          0
Bilbao_wind_speed          0
Seville_clouds_all         0
Bilbao_wind_deg            0
Barcelona_wind_speed       0
Barcelona_wind_deg         0
Madrid_clouds_all          0
Seville_wind_speed         0
Barcelona_rain_1h          0
Seville_rain_1h            0
Bilbao_snow_3h             0
Barcelona_pressure         0
Seville_rain_3h            0
Madrid_rain_1h             0
Barcelona_rain_3h          0
Valencia_snow_3h           0
Madrid_weather_id          0
Barcelona_weather_id       0
Bilbao_pressure            0
Seville_weather_id         0
Valencia_pressure       2522
Seville_temp_max           0
Madrid_pressure            0
Valencia_temp_max          0
Valencia_temp              0
Bilbao_weather_id          0
Seville_temp               0
Valencia_humidity          0
Valencia_temp_min          0
Barcelona_temp_max         0
Madrid_temp_max            0
Barcelona_temp             0
Bilbao_temp_min            0
Bilbao_temp                0
Barcelona_temp_min         0
Bilbao_temp_max            0
Seville_temp_min           0
Madrid_temp                0
Madrid_temp_min            0
dtype: int64

In [423]:
Knn = KNeighborsRegressor()

In [424]:
def Knn_impute( df, column):
    df = df.copy()
    
    numeric_df= df.select_dtypes(np.number)
    
    return numeric_df

In [425]:
Knn_impute(data2, 'load_shortfall_3h ').head()

,Madrid_wind_speed,Bilbao_rain_1h,Valencia_wind_speed,Seville_humidity,Madrid_humidity,Bilbao_clouds_all,Bilbao_wind_speed,Seville_clouds_all,Bilbao_wind_deg,Barcelona_wind_speed,Barcelona_wind_deg,Madrid_clouds_all,Seville_wind_speed,Barcelona_rain_1h,Seville_rain_1h,Bilbao_snow_3h,Barcelona_pressure,Seville_rain_3h,Madrid_rain_1h,Barcelona_rain_3h,Valencia_snow_3h,Madrid_weather_id,Barcelona_weather_id,Bilbao_pressure,Seville_weather_id,Valencia_pressure,Seville_temp_max,Madrid_pressure,Valencia_temp_max,Valencia_temp,Bilbao_weather_id,Seville_temp,Valencia_humidity,Valencia_temp_min,Barcelona_temp_max,Madrid_temp_max,Barcelona_temp,Bilbao_temp_min,Bilbao_temp,Barcelona_temp_min,Bilbao_temp_max,Seville_temp_min,Madrid_temp,Madrid_temp_min
0,0.666667,0.0,0.666667,74.333333,64.000000,0.0,1.000000,0.0,223.333333,6.333333,42.666667,0.0,3.333333,0.0,0.0,0,1036.333333,0.0,0.0,0.0,0,800.0,800.0,1035.000000,800.0,1002.666667,274.254667,971.333333,269.888000,269.888000,800.0,274.254667,75.666667,269.888000,281.013000,265.938000,281.013000,269.338615,269.338615,281.013000,269.338615,274.254667,265.938000,265.938000
1,0.333333,0.0,1.666667,78.333333,64.666667,0.0,1.000000,0.0,221.000000,4.000000,139.000000,0.0,3.333333,0.0,0.0,0,1037.333333,0.0,0.0,0.0,0,800.0,800.0,1035.666667,800.0,1004.333333,274.945000,972.666667,271.728333,271.728333,800.0,274.945000,71.000000,271.728333,280.561667,266.386667,280.561667,270.376000,270.376000,280.561667,270.376000,274.945000,266.386667,266.386667
2,1.000000,0.0,1.000000,71.333333,64.333333,0.0,1.000000,0.0,214.333333,2.000000,326.000000,0.0,2.666667,0.0,0.0,0,1038.000000,0.0,0.0,0.0,0,800.0,800.0,1036.000000,800.0,1005.333333,278.792000,974.000000,278.008667,278.008667,800.0,278.792000,65.666667,278.008667,281.583667,272.708667,281.583667,275.027229,275.027229,281.583667,275.027229,278.792000,272.708667,272.708667
3,1.000000,0.0,1.000000,65.333333,56.333333,0.0,1.000000,0.0,199.666667,2.333333,273.000000,0.0,4.000000,0.0,0.0,0,1037.000000,0.0,0.0,0.0,0,800.0,800.0,1036.000000,800.0,1009.000000,285.394000,994.666667,284.899552,284.899552,800.0,285.394000,54.000000,284.899552,283.434104,281.895219,283.434104,281.135063,281.135063,283.434104,281.135063,285.394000,281.895219,281.895219
4,1.000000,0.0,1.000000,59.000000,57.000000,2.0,0.333333,0.0,185.000000,4.333333,260.000000,0.0,3.000000,0.0,0.0,0,1035.000000,0.0,0.0,0.0,0,800.0,800.0,1035.333333,800.0,NaN,285.513719,1035.333333,283.015115,283.015115,800.0,285.513719,58.333333,283.015115,284.213167,280.678437,284.213167,282.252063,282.252063,284.213167,282.252063,285.513719,280.678437,280.678437

In [426]:
def Knn_impute( df, na_target):
    df = df.copy()
    
    numeric_df= df.select_dtypes(np.number)
    non_na_columns= numeric_df.loc[:, numeric_df.isna().sum()==0].columns
    
    y_train= numeric_df.loc[numeric_df[na_target].isna()== False, na_target]
    X_train= numeric_df.loc[numeric_df[na_target].isna()==False, non_na_columns]
    X_test= numeric_df.loc[numeric_df[na_target].isna()==True, non_na_columns]
    
    Knn = KNeighborsRegressor()
    Knn.fit(X_train, y_train)
    
    y_pred= Knn.predict(X_test)
    df.loc[df[na_target].isna()==True, na_target]= y_pred
    
    return df

In [427]:
Knn_impute(data2, 'Valencia_pressure').head()

,Madrid_wind_speed,Bilbao_rain_1h,Valencia_wind_speed,Seville_humidity,Madrid_humidity,Bilbao_clouds_all,Bilbao_wind_speed,Seville_clouds_all,Bilbao_wind_deg,Barcelona_wind_speed,Barcelona_wind_deg,Madrid_clouds_all,Seville_wind_speed,Barcelona_rain_1h,Seville_rain_1h,Bilbao_snow_3h,Barcelona_pressure,Seville_rain_3h,Madrid_rain_1h,Barcelona_rain_3h,Valencia_snow_3h,Madrid_weather_id,Barcelona_weather_id,Bilbao_pressure,Seville_weather_id,Valencia_pressure,Seville_temp_max,Madrid_pressure,Valencia_temp_max,Valencia_temp,Bilbao_weather_id,Seville_temp,Valencia_humidity,Valencia_temp_min,Barcelona_temp_max,Madrid_temp_max,Barcelona_temp,Bilbao_temp_min,Bilbao_temp,Barcelona_temp_min,Bilbao_temp_max,Seville_temp_min,Madrid_temp,Madrid_temp_min
0,0.666667,0.0,0.666667,74.333333,64.000000,0.0,1.000000,0.0,223.333333,6.333333,42.666667,0.0,3.333333,0.0,0.0,0,1036.333333,0.0,0.0,0.0,0,800.0,800.0,1035.000000,800.0,1002.666667,274.254667,971.333333,269.888000,269.888000,800.0,274.254667,75.666667,269.888000,281.013000,265.938000,281.013000,269.338615,269.338615,281.013000,269.338615,274.254667,265.938000,265.938000
1,0.333333,0.0,1.666667,78.333333,64.666667,0.0,1.000000,0.0,221.000000,4.000000,139.000000,0.0,3.333333,0.0,0.0,0,1037.333333,0.0,0.0,0.0,0,800.0,800.0,1035.666667,800.0,1004.333333,274.945000,972.666667,271.728333,271.728333,800.0,274.945000,71.000000,271.728333,280.561667,266.386667,280.561667,270.376000,270.376000,280.561667,270.376000,274.945000,266.386667,266.386667
2,1.000000,0.0,1.000000,71.333333,64.333333,0.0,1.000000,0.0,214.333333,2.000000,326.000000,0.0,2.666667,0.0,0.0,0,1038.000000,0.0,0.0,0.0,0,800.0,800.0,1036.000000,800.0,1005.333333,278.792000,974.000000,278.008667,278.008667,800.0,278.792000,65.666667,278.008667,281.583667,272.708667,281.583667,275.027229,275.027229,281.583667,275.027229,278.792000,272.708667,272.708667
3,1.000000,0.0,1.000000,65.333333,56.333333,0.0,1.000000,0.0,199.666667,2.333333,273.000000,0.0,4.000000,0.0,0.0,0,1037.000000,0.0,0.0,0.0,0,800.0,800.0,1036.000000,800.0,1009.000000,285.394000,994.666667,284.899552,284.899552,800.0,285.394000,54.000000,284.899552,283.434104,281.895219,283.434104,281.135063,281.135063,283.434104,281.135063,285.394000,281.895219,281.895219
4,1.000000,0.0,1.000000,59.000000,57.000000,2.0,0.333333,0.0,185.000000,4.333333,260.000000,0.0,3.000000,0.0,0.0,0,1035.000000,0.0,0.0,0.0,0,800.0,800.0,1035.333333,800.0,1017.000000,285.513719,1035.333333,283.015115,283.015115,800.0,285.513719,58.333333,283.015115,284.213167,280.678437,284.213167,282.252063,282.252063,284.213167,282.252063,285.513719,280.678437,280.678437

In [428]:
data2.isna().sum()

Madrid_wind_speed          0
Bilbao_rain_1h             0
Valencia_wind_speed        0
Seville_humidity           0
Madrid_humidity            0
Bilbao_clouds_all          0
Bilbao_wind_speed          0
Seville_clouds_all         0
Bilbao_wind_deg            0
Barcelona_wind_speed       0
Barcelona_wind_deg         0
Madrid_clouds_all          0
Seville_wind_speed         0
Barcelona_rain_1h          0
Seville_rain_1h            0
Bilbao_snow_3h             0
Barcelona_pressure         0
Seville_rain_3h            0
Madrid_rain_1h             0
Barcelona_rain_3h          0
Valencia_snow_3h           0
Madrid_weather_id          0
Barcelona_weather_id       0
Bilbao_pressure            0
Seville_weather_id         0
Valencia_pressure       2522
Seville_temp_max           0
Madrid_pressure            0
Valencia_temp_max          0
Valencia_temp              0
Bilbao_weather_id          0
Seville_temp               0
Valencia_humidity          0
Valencia_temp_min          0
Barcelona_temp_max         0
Madrid_temp_max            0
Barcelona_temp             0
Bilbao_temp_min            0
Bilbao_temp                0
Barcelona_temp_min         0
Bilbao_temp_max            0
Seville_temp_min           0
Madrid_temp                0
Madrid_temp_min            0
dtype: int64

In [429]:
data2.columns[data2.isna().sum()>0]

Index(['Valencia_pressure'], dtype='object')

In [430]:
for column in [
    'Valencia_pressure'
]:
    data2 = Knn_impute(data2, column)

In [431]:
data2.isna().sum()

Madrid_wind_speed       0
Bilbao_rain_1h          0
Valencia_wind_speed     0
Seville_humidity        0
Madrid_humidity         0
Bilbao_clouds_all       0
Bilbao_wind_speed       0
Seville_clouds_all      0
Bilbao_wind_deg         0
Barcelona_wind_speed    0
Barcelona_wind_deg      0
Madrid_clouds_all       0
Seville_wind_speed      0
Barcelona_rain_1h       0
Seville_rain_1h         0
Bilbao_snow_3h          0
Barcelona_pressure      0
Seville_rain_3h         0
Madrid_rain_1h          0
Barcelona_rain_3h       0
Valencia_snow_3h        0
Madrid_weather_id       0
Barcelona_weather_id    0
Bilbao_pressure         0
Seville_weather_id      0
Valencia_pressure       0
Seville_temp_max        0
Madrid_pressure         0
Valencia_temp_max       0
Valencia_temp           0
Bilbao_weather_id       0
Seville_temp            0
Valencia_humidity       0
Valencia_temp_min       0
Barcelona_temp_max      0
Madrid_temp_max         0
Barcelona_temp          0
Bilbao_temp_min         0
Bilbao_temp             0
Barcelona_temp_min      0
Bilbao_temp_max         0
Seville_temp_min        0
Madrid_temp             0
Madrid_temp_min         0
dtype: int64

In [432]:
data3=data2.copy()

<a id="five"></a>
## 5. Modelling
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Modelling ⚡ |
| :--------------------------- |
| In this section, you are required to create one or more regression models that are able to accurately predict the thee hour load shortfall. |

---

In [433]:
# split data
import scipy.stats

In [434]:
# create targets and features dataset
data3.select_dtypes(np.number).head()

,Madrid_wind_speed,Bilbao_rain_1h,Valencia_wind_speed,Seville_humidity,Madrid_humidity,Bilbao_clouds_all,Bilbao_wind_speed,Seville_clouds_all,Bilbao_wind_deg,Barcelona_wind_speed,Barcelona_wind_deg,Madrid_clouds_all,Seville_wind_speed,Barcelona_rain_1h,Seville_rain_1h,Bilbao_snow_3h,Barcelona_pressure,Seville_rain_3h,Madrid_rain_1h,Barcelona_rain_3h,Valencia_snow_3h,Madrid_weather_id,Barcelona_weather_id,Bilbao_pressure,Seville_weather_id,Valencia_pressure,Seville_temp_max,Madrid_pressure,Valencia_temp_max,Valencia_temp,Bilbao_weather_id,Seville_temp,Valencia_humidity,Valencia_temp_min,Barcelona_temp_max,Madrid_temp_max,Barcelona_temp,Bilbao_temp_min,Bilbao_temp,Barcelona_temp_min,Bilbao_temp_max,Seville_temp_min,Madrid_temp,Madrid_temp_min
0,0.666667,0.0,0.666667,74.333333,64.000000,0.0,1.000000,0.0,223.333333,6.333333,42.666667,0.0,3.333333,0.0,0.0,0,1036.333333,0.0,0.0,0.0,0,800.0,800.0,1035.000000,800.0,1002.666667,274.254667,971.333333,269.888000,269.888000,800.0,274.254667,75.666667,269.888000,281.013000,265.938000,281.013000,269.338615,269.338615,281.013000,269.338615,274.254667,265.938000,265.938000
1,0.333333,0.0,1.666667,78.333333,64.666667,0.0,1.000000,0.0,221.000000,4.000000,139.000000,0.0,3.333333,0.0,0.0,0,1037.333333,0.0,0.0,0.0,0,800.0,800.0,1035.666667,800.0,1004.333333,274.945000,972.666667,271.728333,271.728333,800.0,274.945000,71.000000,271.728333,280.561667,266.386667,280.561667,270.376000,270.376000,280.561667,270.376000,274.945000,266.386667,266.386667
2,1.000000,0.0,1.000000,71.333333,64.333333,0.0,1.000000,0.0,214.333333,2.000000,326.000000,0.0,2.666667,0.0,0.0,0,1038.000000,0.0,0.0,0.0,0,800.0,800.0,1036.000000,800.0,1005.333333,278.792000,974.000000,278.008667,278.008667,800.0,278.792000,65.666667,278.008667,281.583667,272.708667,281.583667,275.027229,275.027229,281.583667,275.027229,278.792000,272.708667,272.708667
3,1.000000,0.0,1.000000,65.333333,56.333333,0.0,1.000000,0.0,199.666667,2.333333,273.000000,0.0,4.000000,0.0,0.0,0,1037.000000,0.0,0.0,0.0,0,800.0,800.0,1036.000000,800.0,1009.000000,285.394000,994.666667,284.899552,284.899552,800.0,285.394000,54.000000,284.899552,283.434104,281.895219,283.434104,281.135063,281.135063,283.434104,281.135063,285.394000,281.895219,281.895219
4,1.000000,0.0,1.000000,59.000000,57.000000,2.0,0.333333,0.0,185.000000,4.333333,260.000000,0.0,3.000000,0.0,0.0,0,1035.000000,0.0,0.0,0.0,0,800.0,800.0,1035.333333,800.0,1017.000000,285.513719,1035.333333,283.015115,283.015115,800.0,285.513719,58.333333,283.015115,284.213167,280.678437,284.213167,282.252063,282.252063,284.213167,282.252063,285.513719,280.678437,280.678437

In [435]:
#data3['load_shortfall_3h']=target

In [436]:
scipy.stats.skew(data3['Madrid_wind_speed'])

1.4526054166488407

In [437]:
scipy.stats.skew(data3.select_dtypes(np.number))

array([ 1.45260542e+00,  5.69380748e+00,  3.11595219e+00, -3.65986066e-01,
       -7.65804567e-02, -6.83262488e-02,  1.60231628e+00,  1.76487762e+00,
        2.46816200e-01,  1.07227907e+00, -1.40319278e-01,  1.15833748e+00,
        1.21328106e+00,  9.83192870e+00,  7.53497634e+00,  3.19420742e+01,
        6.69404570e+01,  2.23462978e+01,  6.44568602e+00,  1.46670398e+01,
        0.00000000e+00, -2.90868010e+00, -2.59508377e+00, -9.77405968e-01,
       -3.23008368e+00, -2.04985335e+00,  1.22146686e-01, -2.13997424e+00,
        6.82684734e-02,  4.58539990e-02, -1.31692099e+00,  2.19813692e-01,
       -2.92609268e-01,  6.95170587e-02,  2.41511170e-01,  3.21134297e-01,
        1.05566377e-01,  2.02514444e-01,  2.70514864e-01,  2.28784681e-03,
        3.31264143e-01,  3.05552979e-01,  3.25072650e-01,  2.96367367e-01])

In [438]:
skew_df =pd.DataFrame(data3.select_dtypes(np.number).columns, columns=['feature'])
skew_df['skew']=skew_df['feature'].apply(lambda feature: scipy.stats.skew(data3[feature]))
skew_df['Absolute_skew']= skew_df['skew'].apply(abs)
skew_df['skewed']=skew_df['Absolute_skew'].apply(lambda x: True if x >= 0.5 else False)

skew_df.head()

               feature      skew  Absolute_skew  skewed
0    Madrid_wind_speed  1.452605       1.452605    True
1       Bilbao_rain_1h  5.693807       5.693807    True
2  Valencia_wind_speed  3.115952       3.115952    True
3     Seville_humidity -0.365986       0.365986   False
4      Madrid_humidity -0.076580       0.076580   False

In [439]:
skew_df.query("skewed == True")['feature']

0        Madrid_wind_speed
1           Bilbao_rain_1h
2      Valencia_wind_speed
6        Bilbao_wind_speed
7       Seville_clouds_all
9     Barcelona_wind_speed
11       Madrid_clouds_all
12      Seville_wind_speed
13       Barcelona_rain_1h
14         Seville_rain_1h
15          Bilbao_snow_3h
16      Barcelona_pressure
17         Seville_rain_3h
18          Madrid_rain_1h
19       Barcelona_rain_3h
21       Madrid_weather_id
22    Barcelona_weather_id
23         Bilbao_pressure
24      Seville_weather_id
25       Valencia_pressure
27         Madrid_pressure
30       Bilbao_weather_id
Name: feature, dtype: object

In [440]:
data3[skew_df.query("skewed == True")['feature'].values].describe()

,Madrid_wind_speed,Bilbao_rain_1h,Valencia_wind_speed,Bilbao_wind_speed,Seville_clouds_all,Barcelona_wind_speed,Madrid_clouds_all,Seville_wind_speed,Barcelona_rain_1h,Seville_rain_1h,Bilbao_snow_3h,Barcelona_pressure,Seville_rain_3h,Madrid_rain_1h,Barcelona_rain_3h,Madrid_weather_id,Barcelona_weather_id,Bilbao_pressure,Seville_weather_id,Valencia_pressure,Madrid_pressure,Bilbao_weather_id
count,11683.000000,11683.000000,11683.000000,11683.000000,11683.000000,11683.000000,11683.000000,11683.000000,11683.000000,11683.000000,11683.000000,1.168300e+04,11683.000000,11683.000000,11683.000000,11683.000000,11683.000000,11683.000000,11683.000000,11683.000000,11683.000000,11683.000000
mean,2.433750,0.118698,2.692873,1.958629,14.155268,2.782419,20.668692,2.483067,0.108534,0.041120,0.020371,1.287326e+03,0.000182,0.043328,0.000331,769.851665,764.603446,1017.482011,774.050843,1013.254792,1011.797412,727.800750
std,1.831762,0.334918,2.321759,1.696043,24.541321,1.758587,28.478087,1.705508,0.556794,0.180425,0.455441,1.218906e+04,0.003171,0.163996,0.003466,81.914258,90.736191,9.753552,72.909418,8.211355,19.983122,113.616789
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.706667e+02,0.000000,0.000000,0.000000,211.000000,200.666667,971.333333,200.000000,972.666667,927.666667,207.333333
25%,1.000000,0.000000,1.000000,1.000000,0.000000,1.333333,0.000000,1.000000,0.000000,0.000000,0.000000,1.013667e+03,0.000000,0.000000,0.000000,800.000000,800.000000,1013.333333,800.000000,1012.000000,1012.666667,701.000000
50%,2.000000,0.000000,2.000000,1.333333,0.000000,2.333333,0.000000,2.000000,0.000000,0.000000,0.000000,1.017333e+03,0.000000,0.000000,0.000000,800.000000,800.000000,1018.666667,800.000000,1016.000000,1017.333333,800.000000
75%,3.333333,0.100000,3.666667,2.666667,20.000000,3.666667,38.333333,3.333333,0.000000,0.000000,0.000000,1.021167e+03,0.000000,0.000000,0.000000,800.666667,801.000000,1023.333333,800.000000,1018.333333,1021.666667,801.666667
max,13.333333,3.000000,52.000000,12.666667,97.333333,12.666667,100.000000,12.666667,12.000000,3.000000,21.000000,1.001411e+06,0.093333,3.000000,0.093000,804.000000,804.000000,1042.000000,804.000000,1021.666667,1038.000000,804.000000

In [441]:
for column in skew_df.query("skewed == True")['feature'].values:
    data3[column] = np.log1p(data3[column])

In [442]:
skew_df =pd.DataFrame(data3.select_dtypes(np.number).columns, columns=['feature'])
skew_df['skew']=skew_df['feature'].apply(lambda feature: scipy.stats.skew(data3[feature]))
skew_df['Absolute_skew']= skew_df['skew'].apply(abs)
skew_df['skewed']=skew_df['Absolute_skew'].apply(lambda x: True if x >= 0.5 else False)

skew_df.head()

               feature      skew  Absolute_skew  skewed
0    Madrid_wind_speed  0.398125       0.398125   False
1       Bilbao_rain_1h  3.559209       3.559209    True
2  Valencia_wind_speed  0.390219       0.390219   False
3     Seville_humidity -0.365986       0.365986   False
4      Madrid_humidity -0.076580       0.076580   False

In [443]:
data4=data3.copy()

In [444]:
data4=pd.get_dummies(data4)
data4.head()

,Madrid_wind_speed,Bilbao_rain_1h,Valencia_wind_speed,Seville_humidity,Madrid_humidity,Bilbao_clouds_all,Bilbao_wind_speed,Seville_clouds_all,Bilbao_wind_deg,Barcelona_wind_speed,Barcelona_wind_deg,Madrid_clouds_all,Seville_wind_speed,Barcelona_rain_1h,Seville_rain_1h,Bilbao_snow_3h,Barcelona_pressure,Seville_rain_3h,Madrid_rain_1h,Barcelona_rain_3h,Valencia_snow_3h,Madrid_weather_id,Barcelona_weather_id,Bilbao_pressure,Seville_weather_id,Valencia_pressure,Seville_temp_max,Madrid_pressure,Valencia_temp_max,Valencia_temp,Bilbao_weather_id,Seville_temp,Valencia_humidity,Valencia_temp_min,Barcelona_temp_max,Madrid_temp_max,Barcelona_temp,Bilbao_temp_min,Bilbao_temp,Barcelona_temp_min,Bilbao_temp_max,Seville_temp_min,Madrid_temp,Madrid_temp_min
0,0.510826,0.0,0.510826,74.333333,64.000000,0.0,0.693147,0.0,223.333333,1.992430,42.666667,0.0,1.466337,0.0,0.0,0.0,6.944409,0.0,0.0,0.0,0,6.685861,6.685861,6.943122,6.685861,6.911415,274.254667,6.879699,269.888000,269.888000,6.685861,274.254667,75.666667,269.888000,281.013000,265.938000,281.013000,269.338615,269.338615,281.013000,269.338615,274.254667,265.938000,265.938000
1,0.287682,0.0,0.980829,78.333333,64.666667,0.0,0.693147,0.0,221.000000,1.609438,139.000000,0.0,1.466337,0.0,0.0,0.0,6.945372,0.0,0.0,0.0,0,6.685861,6.685861,6.943766,6.685861,6.913074,274.945000,6.881069,271.728333,271.728333,6.685861,274.945000,71.000000,271.728333,280.561667,266.386667,280.561667,270.376000,270.376000,280.561667,270.376000,274.945000,266.386667,266.386667
2,0.693147,0.0,0.693147,71.333333,64.333333,0.0,0.693147,0.0,214.333333,1.098612,326.000000,0.0,1.299283,0.0,0.0,0.0,6.946014,0.0,0.0,0.0,0,6.685861,6.685861,6.944087,6.685861,6.914069,278.792000,6.882437,278.008667,278.008667,6.685861,278.792000,65.666667,278.008667,281.583667,272.708667,281.583667,275.027229,275.027229,281.583667,275.027229,278.792000,272.708667,272.708667
3,0.693147,0.0,0.693147,65.333333,56.333333,0.0,0.693147,0.0,199.666667,1.203973,273.000000,0.0,1.609438,0.0,0.0,0.0,6.945051,0.0,0.0,0.0,0,6.685861,6.685861,6.944087,6.685861,6.917706,285.394000,6.903413,284.899552,284.899552,6.685861,285.394000,54.000000,284.899552,283.434104,281.895219,283.434104,281.135063,281.135063,283.434104,281.135063,285.394000,281.895219,281.895219
4,0.693147,0.0,0.693147,59.000000,57.000000,2.0,0.287682,0.0,185.000000,1.673976,260.000000,0.0,1.386294,0.0,0.0,0.0,6.943122,0.0,0.0,0.0,0,6.685861,6.685861,6.943444,6.685861,6.925595,285.513719,6.943444,283.015115,283.015115,6.685861,285.513719,58.333333,283.015115,284.213167,280.678437,284.213167,282.252063,282.252063,284.213167,282.252063,285.513719,280.678437,280.678437

In [445]:
data5=data4.copy()

In [446]:
from sklearn.preprocessing import StandardScaler

In [447]:
# scalling
scaler=StandardScaler()
scaler.fit(data4)

data5=pd.DataFrame(scaler.transform(data5), index=data5.index, columns=data5.columns)

In [448]:
data5.head()

,Madrid_wind_speed,Bilbao_rain_1h,Valencia_wind_speed,Seville_humidity,Madrid_humidity,Bilbao_clouds_all,Bilbao_wind_speed,Seville_clouds_all,Bilbao_wind_deg,Barcelona_wind_speed,Barcelona_wind_deg,Madrid_clouds_all,Seville_wind_speed,Barcelona_rain_1h,Seville_rain_1h,Bilbao_snow_3h,Barcelona_pressure,Seville_rain_3h,Madrid_rain_1h,Barcelona_rain_3h,Valencia_snow_3h,Madrid_weather_id,Barcelona_weather_id,Bilbao_pressure,Seville_weather_id,Valencia_pressure,Seville_temp_max,Madrid_pressure,Valencia_temp_max,Valencia_temp,Bilbao_weather_id,Seville_temp,Valencia_humidity,Valencia_temp_min,Barcelona_temp_max,Madrid_temp_max,Barcelona_temp,Bilbao_temp_min,Bilbao_temp,Barcelona_temp_min,Bilbao_temp_max,Seville_temp_min,Madrid_temp,Madrid_temp_min
0,-1.257907,-0.445987,-1.208327,0.475220,0.216411,-1.355623,-0.494626,-0.742149,0.628254,1.661214,-1.634751,-0.924886,0.703062,-0.27126,-0.26046,-0.058091,0.063439,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.777042,0.337435,-1.281332,-2.436246,-2.011975,-2.886015,-2.920074,0.609908,-2.364999,0.555399,-2.904614,-1.385995,-2.443090,-1.325760,-2.326231,-2.539139,-1.189628,-2.719042,-2.090559,-2.413444,-2.322453
1,-1.723994,-0.445987,-0.327175,0.655251,0.243745,-1.355623,-0.494626,-0.742149,0.605152,0.830926,-0.548582,-0.924886,0.703062,-0.27126,-0.26046,-0.058091,0.068709,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.843893,0.337435,-1.078103,-2.358930,-1.944021,-2.638690,-2.662955,0.609908,-2.278690,0.310302,-2.641834,-1.448368,-2.396325,-1.393323,-2.172083,-2.385183,-1.260241,-2.568659,-2.005709,-2.364982,-2.273112
2,-0.877085,-0.445987,-0.866515,0.340197,0.230078,-1.355623,-0.494626,-0.742149,0.539146,-0.276493,1.559864,-0.924886,0.345499,-0.27126,-0.26046,-0.058091,0.072219,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.877303,0.337435,-0.956327,-1.928076,-1.876159,-1.794668,-1.785511,0.609908,-1.797721,0.030192,-1.745068,-1.307130,-1.737382,-1.240334,-1.480942,-1.694903,-1.100346,-1.894402,-1.532866,-1.682125,-1.577857
3,-0.877085,-0.445987,-0.866515,0.070151,-0.097931,-1.355623,-0.494626,-0.742149,0.393934,-0.048082,0.962283,-0.924886,1.009356,-0.27126,-0.26046,-0.058091,0.066953,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.877303,0.337435,-0.510849,-1.188669,-0.836012,-0.868594,-0.822765,0.609908,-0.972309,-0.582550,-0.761123,-1.051406,-0.779866,-0.963333,-0.573360,-0.788451,-0.810840,-1.008992,-0.721399,-0.689860,-0.567576
4,-0.877085,-0.445987,-0.866515,-0.214898,-0.070596,-1.293210,-1.285015,-0.742149,0.248721,0.970839,0.815706,-0.924886,0.531739,-0.27126,-0.26046,-0.058091,0.056405,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.810473,0.337435,0.455514,-1.175261,1.149142,-1.121846,-1.086045,0.609908,-0.957341,-0.354960,-1.030201,-0.943742,-0.906691,-0.846712,-0.407382,-0.622679,-0.688954,-0.847068,-0.706684,-0.821288,-0.701390

**TARGET TRANSFORMATION**

In [449]:
target.hist()

In [450]:
np.min(target)

-6618.0

In [451]:
#target1=-target

In [452]:
#np.min(target1)

In [453]:
plt.figure(figsize=(15, 10))

plt.subplot(1, 2, 1)
sns.distplot(target, kde=True, fit=scipy.stats.norm)
plt.title('with_log_transform')
plt.subplot(1, 2, 1)
sns.distplot(target, kde=True, fit=scipy.stats.norm)
plt.title('without_log_transform')
plt.show()

C:\Users\allym\anaconda3\lib\site-packages\seaborn\distributions.py:2619: FutureWarning: `distplot` is a deprecated function and will be removed in a future version. Please adapt your code to use either `displot` (a figure-level function with similar flexibility) or `histplot` (an axes-level function for histograms).
  warnings.warn(msg, FutureWarning)
C:\Users\allym\anaconda3\lib\site-packages\seaborn\distributions.py:2619: FutureWarning: `distplot` is a deprecated function and will be removed in a future version. Please adapt your code to use either `displot` (a figure-level function with similar flexibility) or `histplot` (an axes-level function for histograms).
  warnings.warn(msg, FutureWarning)

In [454]:
log_target = np.log(target)

C:\Users\allym\anaconda3\lib\site-packages\pandas\core\arraylike.py:364: RuntimeWarning: invalid value encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [455]:
log_target.isna().sum()

317

**SPLITTING DATA**

In [456]:
train_final = data5.loc[:train0.index.max(), :].copy()
test_final = data5.loc[train0.index.max() +1:, :].reset_index(drop=True).copy()

In [457]:
train_final.head()

,Madrid_wind_speed,Bilbao_rain_1h,Valencia_wind_speed,Seville_humidity,Madrid_humidity,Bilbao_clouds_all,Bilbao_wind_speed,Seville_clouds_all,Bilbao_wind_deg,Barcelona_wind_speed,Barcelona_wind_deg,Madrid_clouds_all,Seville_wind_speed,Barcelona_rain_1h,Seville_rain_1h,Bilbao_snow_3h,Barcelona_pressure,Seville_rain_3h,Madrid_rain_1h,Barcelona_rain_3h,Valencia_snow_3h,Madrid_weather_id,Barcelona_weather_id,Bilbao_pressure,Seville_weather_id,Valencia_pressure,Seville_temp_max,Madrid_pressure,Valencia_temp_max,Valencia_temp,Bilbao_weather_id,Seville_temp,Valencia_humidity,Valencia_temp_min,Barcelona_temp_max,Madrid_temp_max,Barcelona_temp,Bilbao_temp_min,Bilbao_temp,Barcelona_temp_min,Bilbao_temp_max,Seville_temp_min,Madrid_temp,Madrid_temp_min
0,-1.257907,-0.445987,-1.208327,0.475220,0.216411,-1.355623,-0.494626,-0.742149,0.628254,1.661214,-1.634751,-0.924886,0.703062,-0.27126,-0.26046,-0.058091,0.063439,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.777042,0.337435,-1.281332,-2.436246,-2.011975,-2.886015,-2.920074,0.609908,-2.364999,0.555399,-2.904614,-1.385995,-2.443090,-1.325760,-2.326231,-2.539139,-1.189628,-2.719042,-2.090559,-2.413444,-2.322453
1,-1.723994,-0.445987,-0.327175,0.655251,0.243745,-1.355623,-0.494626,-0.742149,0.605152,0.830926,-0.548582,-0.924886,0.703062,-0.27126,-0.26046,-0.058091,0.068709,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.843893,0.337435,-1.078103,-2.358930,-1.944021,-2.638690,-2.662955,0.609908,-2.278690,0.310302,-2.641834,-1.448368,-2.396325,-1.393323,-2.172083,-2.385183,-1.260241,-2.568659,-2.005709,-2.364982,-2.273112
2,-0.877085,-0.445987,-0.866515,0.340197,0.230078,-1.355623,-0.494626,-0.742149,0.539146,-0.276493,1.559864,-0.924886,0.345499,-0.27126,-0.26046,-0.058091,0.072219,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.877303,0.337435,-0.956327,-1.928076,-1.876159,-1.794668,-1.785511,0.609908,-1.797721,0.030192,-1.745068,-1.307130,-1.737382,-1.240334,-1.480942,-1.694903,-1.100346,-1.894402,-1.532866,-1.682125,-1.577857
3,-0.877085,-0.445987,-0.866515,0.070151,-0.097931,-1.355623,-0.494626,-0.742149,0.393934,-0.048082,0.962283,-0.924886,1.009356,-0.27126,-0.26046,-0.058091,0.066953,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.877303,0.337435,-0.510849,-1.188669,-0.836012,-0.868594,-0.822765,0.609908,-0.972309,-0.582550,-0.761123,-1.051406,-0.779866,-0.963333,-0.573360,-0.788451,-0.810840,-1.008992,-0.721399,-0.689860,-0.567576
4,-0.877085,-0.445987,-0.866515,-0.214898,-0.070596,-1.293210,-1.285015,-0.742149,0.248721,0.970839,0.815706,-0.924886,0.531739,-0.27126,-0.26046,-0.058091,0.056405,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.810473,0.337435,0.455514,-1.175261,1.149142,-1.121846,-1.086045,0.609908,-0.957341,-0.354960,-1.030201,-0.943742,-0.906691,-0.846712,-0.407382,-0.622679,-0.688954,-0.847068,-0.706684,-0.821288,-0.701390

In [458]:
target.isna().sum()

0

In [459]:
test_time.isna().sum()

0

In [460]:
test_final

,Madrid_wind_speed,Bilbao_rain_1h,Valencia_wind_speed,Seville_humidity,Madrid_humidity,Bilbao_clouds_all,Bilbao_wind_speed,Seville_clouds_all,Bilbao_wind_deg,Barcelona_wind_speed,Barcelona_wind_deg,Madrid_clouds_all,Seville_wind_speed,Barcelona_rain_1h,Seville_rain_1h,Bilbao_snow_3h,Barcelona_pressure,Seville_rain_3h,Madrid_rain_1h,Barcelona_rain_3h,Valencia_snow_3h,Madrid_weather_id,Barcelona_weather_id,Bilbao_pressure,Seville_weather_id,Valencia_pressure,Seville_temp_max,Madrid_pressure,Valencia_temp_max,Valencia_temp,Bilbao_weather_id,Seville_temp,Valencia_humidity,Valencia_temp_min,Barcelona_temp_max,Madrid_temp_max,Barcelona_temp,Bilbao_temp_min,Bilbao_temp,Barcelona_temp_min,Bilbao_temp_max,Seville_temp_min,Madrid_temp,Madrid_temp_min
0,1.417624,-0.445987,1.193139,1.045318,0.517086,-0.731497,0.856554,-0.742149,0.331228,0.830926,-0.123886,-0.924886,-0.951876,-0.27126,-0.26046,-0.058091,-0.037661,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,0.836578,0.337435,0.407377,-1.290662,0.893277,-0.521356,-0.461777,0.616889,-1.187435,-0.985209,-0.392186,-0.445749,-0.892284,-0.376145,-1.314106,-0.900508,-0.281630,-0.426974,-0.997214,-0.908970,-0.869478
1,1.298235,-0.445987,1.294503,1.135333,0.790427,-1.355623,1.157046,-0.742149,-0.163815,1.102267,0.890874,-0.924886,-1.342118,-0.27126,-0.26046,-0.058091,-0.021573,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.377263,0.937750,0.337435,0.647876,-1.514656,0.909308,-0.969327,-0.927487,0.028932,-1.437484,-0.600057,-0.868151,-0.860340,-0.927027,-0.850180,-1.066451,-0.807011,-0.803138,-0.571937,-1.243039,-0.981698,-0.979452
2,0.189894,-0.445987,1.193139,1.135333,1.268774,-1.355623,0.501147,0.454409,-0.295826,0.830926,0.853290,-0.924886,-1.342118,-0.27126,-0.26046,-0.058091,-0.007312,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,0.802832,0.341066,0.647876,-1.701319,0.925333,-1.148515,-1.113771,0.609908,-1.570010,-1.212798,-1.058537,-0.906405,-1.343948,-1.005862,-1.215044,-1.076124,-1.063893,-0.861863,-1.324980,-1.289895,-1.199400
3,0.388971,-0.445987,1.294503,1.330366,0.981766,-0.523455,1.852327,0.454409,0.364231,-0.048082,-1.138646,-0.924886,-0.621932,-0.27126,-0.26046,-0.058091,0.006912,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,0.769075,0.341066,0.343164,-1.663986,1.005381,-1.058921,-1.020629,0.619214,-1.654609,-1.055236,-0.963344,-0.952471,-1.274461,-0.999874,-0.868327,-0.698673,-1.011742,-0.523616,-1.488863,-1.331660,-1.382690
4,1.036803,-0.445987,2.087266,0.070151,0.216411,-0.523455,2.943208,-0.742149,0.727262,1.102267,1.078792,-0.924886,-0.951876,-0.27126,-0.26046,-0.058091,0.008687,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.377263,0.498624,0.337435,0.671899,-0.992002,1.005381,-0.566153,-0.508348,0.619214,-0.950305,-1.265319,-0.439783,-0.491815,-0.857540,-0.456981,-0.472079,-0.345957,-0.385932,-0.185369,-0.833331,-0.820399,-0.759504
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2915,-1.723994,-0.445987,-0.106358,0.805277,-0.371271,1.140879,-0.194134,-0.742149,-0.889878,1.661214,1.492213,-0.924886,-0.084017,-0.27126,-0.26046,-0.058091,0.028178,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.743600,0.337435,0.823942,-1.701319,0.973377,-1.551689,-1.601835,0.131316,-1.620436,0.240274,-1.629695,-1.551324,-0.822797,-1.755834,-2.106603,-1.964594,-1.898306,-1.731642,-1.406921,-1.444353,-1.749269
2916,-1.723994,-0.445987,-0.577516,-0.124882,-1.245962,0.412733,-0.494626,-0.742149,-1.219907,0.158541,1.191544,-0.924886,1.009356,-0.27126,-0.26046,-0.058091,0.022869,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.710147,0.337435,0.615836,-0.954669,0.957367,-0.073385,-0.064992,0.231860,-0.736513,-1.738005,-0.059011,-0.630012,-0.162673,-0.556777,-1.016920,-1.187925,-0.438083,-1.345074,-0.505565,-0.553608,-0.722846
2917,-0.877085,-0.445987,0.432982,-0.754990,-1.327964,-1.355623,-0.850032,-0.742149,-1.437725,0.158541,0.515037,-0.924886,1.277256,-0.27126,-0.26046,-0.058091,0.014010,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.576229,0.337435,0.687913,-0.581345,0.893277,0.284992,0.376502,0.609908,-0.294343,-2.175678,0.464550,-0.215421,-0.058442,-0.157092,-0.125362,-0.203980,-0.073027,-0.330332,-0.054887,-0.059269,-0.063003
2918,-0.877085,-0.445987,-0.106358,-0.499946,-0.084264,-1.355623,-0.850032,-0.742149,-1.394822,-0.048082,0.740539,-0.924886,0.703062,-0.27126,-0.26046,-0.058091,0.014010,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.609725,0.337435,0.735940,-0.805339,0.909308,-0.655747,-0.672278,0.609908,-0.608988,-0.319946,-0.677765,-0.722143,-0.440620,-0.807766,-0.719734,-0.715493,-0.855289,-0.765221,-0.464594,-0.482679,-0.539556
2919,-0.555106,-0.445987,0.091170,-0.094877,0.435084,-1.355623,-0.194134,-0.742149,-0.394835,1.102267,1.379462,-0.924886,0.861683,-0.27126,-0.26046,-0.058091,0.019327,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,1.676684,0.337435,0.919871,-1.253329,0.925333,-1.372501,-1.463519,0.609908,-1.093666,0.730468,-1.534502,-0.998537,-1.309204,-1.307747,-1.314106,-1.483752,-1.585401,-1.635000,-0.915273,-1.259291,-1.162742

In [461]:
test_final.head()

,Madrid_wind_speed,Bilbao_rain_1h,Valencia_wind_speed,Seville_humidity,Madrid_humidity,Bilbao_clouds_all,Bilbao_wind_speed,Seville_clouds_all,Bilbao_wind_deg,Barcelona_wind_speed,Barcelona_wind_deg,Madrid_clouds_all,Seville_wind_speed,Barcelona_rain_1h,Seville_rain_1h,Bilbao_snow_3h,Barcelona_pressure,Seville_rain_3h,Madrid_rain_1h,Barcelona_rain_3h,Valencia_snow_3h,Madrid_weather_id,Barcelona_weather_id,Bilbao_pressure,Seville_weather_id,Valencia_pressure,Seville_temp_max,Madrid_pressure,Valencia_temp_max,Valencia_temp,Bilbao_weather_id,Seville_temp,Valencia_humidity,Valencia_temp_min,Barcelona_temp_max,Madrid_temp_max,Barcelona_temp,Bilbao_temp_min,Bilbao_temp,Barcelona_temp_min,Bilbao_temp_max,Seville_temp_min,Madrid_temp,Madrid_temp_min
0,1.417624,-0.445987,1.193139,1.045318,0.517086,-0.731497,0.856554,-0.742149,0.331228,0.830926,-0.123886,-0.924886,-0.951876,-0.27126,-0.26046,-0.058091,-0.037661,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,0.836578,0.337435,0.407377,-1.290662,0.893277,-0.521356,-0.461777,0.616889,-1.187435,-0.985209,-0.392186,-0.445749,-0.892284,-0.376145,-1.314106,-0.900508,-0.281630,-0.426974,-0.997214,-0.908970,-0.869478
1,1.298235,-0.445987,1.294503,1.135333,0.790427,-1.355623,1.157046,-0.742149,-0.163815,1.102267,0.890874,-0.924886,-1.342118,-0.27126,-0.26046,-0.058091,-0.021573,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.377263,0.937750,0.337435,0.647876,-1.514656,0.909308,-0.969327,-0.927487,0.028932,-1.437484,-0.600057,-0.868151,-0.860340,-0.927027,-0.850180,-1.066451,-0.807011,-0.803138,-0.571937,-1.243039,-0.981698,-0.979452
2,0.189894,-0.445987,1.193139,1.135333,1.268774,-1.355623,0.501147,0.454409,-0.295826,0.830926,0.853290,-0.924886,-1.342118,-0.27126,-0.26046,-0.058091,-0.007312,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,0.802832,0.341066,0.647876,-1.701319,0.925333,-1.148515,-1.113771,0.609908,-1.570010,-1.212798,-1.058537,-0.906405,-1.343948,-1.005862,-1.215044,-1.076124,-1.063893,-0.861863,-1.324980,-1.289895,-1.199400
3,0.388971,-0.445987,1.294503,1.330366,0.981766,-0.523455,1.852327,0.454409,0.364231,-0.048082,-1.138646,-0.924886,-0.621932,-0.27126,-0.26046,-0.058091,0.006912,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.374397,0.769075,0.341066,0.343164,-1.663986,1.005381,-1.058921,-1.020629,0.619214,-1.654609,-1.055236,-0.963344,-0.952471,-1.274461,-0.999874,-0.868327,-0.698673,-1.011742,-0.523616,-1.488863,-1.331660,-1.382690
4,1.036803,-0.445987,2.087266,0.070151,0.216411,-0.523455,2.943208,-0.742149,0.727262,1.102267,1.078792,-0.924886,-0.951876,-0.27126,-0.26046,-0.058091,0.008687,-0.057911,-0.294383,-0.096201,0.0,0.351351,0.377263,0.498624,0.337435,0.671899,-0.992002,1.005381,-0.566153,-0.508348,0.619214,-0.950305,-1.265319,-0.439783,-0.491815,-0.857540,-0.456981,-0.472079,-0.345957,-0.385932,-0.185369,-0.833331,-0.820399,-0.759504

In [462]:
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.metrics import mean_squared_error, r2_score

In [463]:
X_train= train_final
y_train=target
X_test=test_final

In [464]:
from sklearn.linear_model import LinearRegression

In [465]:
lm=LinearRegression()

In [466]:
lm.fit(X_train, y_train)

LinearRegression()

In [467]:
y_pred=lm.predict(X_test)

In [471]:
final_prediction = pd.DataFrame({"time": test_time, "load_shortfall_3h":y_pred}).set_index('time')
final_prediction

                     load_shortfall_3h
time
2018-01-01 00:00:00        9085.974643
2018-01-01 03:00:00        8445.743970
2018-01-01 06:00:00        9389.506599
2018-01-01 09:00:00        9236.187408
2018-01-01 12:00:00        9051.837714
...                                ...
2018-12-31 09:00:00        9024.398437
2018-12-31 12:00:00       10838.757513
2018-12-31 15:00:00       12291.648093
2018-12-31 18:00:00       11693.502790
2018-12-31 21:00:00       10154.719565

[2920 rows x 1 columns]

In [472]:
res = final_prediction.to_csv('linearModel.csv')

<a id="six"></a>
## 6. Model Performance
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Model performance ⚡ |
| :--------------------------- |
| In this section you are required to compare the relative performance of the various trained ML models on a holdout dataset and comment on what model is the best and why. |

---

In [468]:
# Compare model performance

In [469]:
# Choose best model and motivate why it is the best choice

<a id="seven"></a>
## 7. Model Explanations
<a class="anchor" id="1.1"></a>
<a href=#cont>Back to Table of Contents</a>

---
    
| ⚡ Description: Model explanation ⚡ |
| :--------------------------- |
| In this section, you are required to discuss how the best performing model works in a simple way so that both technical and non-technical stakeholders can grasp the intuition behind the model's inner workings. |

---

In [470]:
# discuss chosen methods logic